---
title: "Figures"
author: "Lex Rosenberg"
date: "2023-07-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(patchwork)
library(cowplot)
library(ggpubr)
library(ggrepel)
```

### Load data

```{r}
fishbase_data <- read_csv(here::here("01_data", "02_processed_data", "fishbase_data.csv"))

filled_data <- read_csv(here::here("01_data", "02_processed_data", "filled_data.csv"))

filled_data2 <- read_csv(here::here("01_data", "02_processed_data", "filled_data2.csv")) %>%
  mutate_if(is.character, as.factor)
```

### Plot Homerange vs PLD and current classes

```{r}
# homerange vs PLD
fishbase_data_gmm <- filled_data2 %>%
  mutate(class2 = as.factor(class2))

hr_hist <- ggplot(fishbase_data_gmm, aes(log(home_range))) +
  geom_histogram() +
  theme_bw(base_size = 16) +
  labs(
    y = "Count",
    x = "ln(Predicted Home Range)",
    tag = "A"
  ) +
  ggtitle("Individual Distributions of Species Movement Extents")

pld_hist <- ggplot(fishbase_data_gmm, aes(pld)) +
  geom_histogram() +
  theme_bw(base_size = 16) +
  labs(
    y = "Count",
    x = "Predicted PLD"
  )

dist_plot <- (hr_hist / pld_hist)

p1 <- ggplot(fishbase_data_gmm, aes(log(home_range), pld)) +
  geom_jitter() +
  theme_bw(base_size = 16) +
  labs(
    y = "Predicted PLD",
    x = "ln(Predicted Home Range)",
    tag = "B"
  ) +
  ggtitle("Combined Distribution of Species Movement Extents")

p1



# gmm plot


# example_fish <- filled_data2 %>%
#   select(species, fb_name, class2, class3, magnitude_homerange, month_pld) %>%
#   filter(fb_name %in% c(
#     "Hogfish", "Yellow snapper", "Blackfin tuna", "Humphead wrasse", "Pacific red snapper",
#     "Giant seabass", "Lemon sole", "Chum salmon", "Pacific ocean perch", "Atlantic herring",
#     "Atlantic cod", "Haddock", "Atlantic salmon", "California sheephead", "Black seabream",
#     "Blue marlin", "Yellowfin tuna", "Swordfish"
#     # "Blackhead seabream", "Pink salmon", "Coho salmon", "Ghost shark", "Pollack", "Polar cod", "Sockeye salmon", "Chinook salmon"
#   ))


gmm_new_fig <- ggplot(fishbase_data_gmm, aes(magnitude_homerange, month_pld)) +
  theme_bw(base_size = 16) +
  labs(
    x = "Predicted Home Range Magnitude",
    y = "Predicted PLD Month",
    color = "Cohort (Homerange/PLD)",
    tag = "C"
  ) +
  ylim(-0.1,6) +
  theme(legend.position = "bottom") +
  scale_color_viridis_d() +
  geom_label_repel(
    data = subset(fishbase_data_gmm, fb_name %in% c("Hogfish", "Yellow snapper", "Blackfin tuna")),
    aes(label = fb_name, color = class2),
    vjust = "outward", hjust = "outward",
    min.segment.length = 0.5,
    nudge_y = -1,
    show.legend = FALSE
  ) +
  geom_label_repel(
    data = subset(fishbase_data_gmm, fb_name %in% c("Chocolate hind", "Lingcod", "Nassau grouper")),
    aes(label = fb_name, color = class2),
    hjust = "inward",
    min.segment.length = 0.5,
    box.padding = 0.3,
    nudge_x = -2, nudge_y = -0.8,
    show.legend = FALSE
  ) +
  geom_label_repel(
    data = subset(fishbase_data_gmm, fb_name %in% c("Lemon sole", "North Pacific hake", "Yellowstripe goatfish")),
    aes(label = fb_name, color = class2),
    vjust = "outward", hjust = "outward",
    min.segment.length = 0.5,
    nudge_x = -1, nudge_y = 0.8,
    show.legend = FALSE
  ) +
  geom_label_repel(
    data = subset(fishbase_data_gmm, fb_name %in% c("Atlantic herring", "Atlantic cod", "Summer flounder")),
    aes(label = fb_name, color = class2),
    vjust = "outward", hjust = "outward",
    min.segment.length = 0.5,
    nudge_y = 0,
    show.legend = FALSE
  ) +
  geom_label_repel(
    data = subset(fishbase_data_gmm, fb_name %in% c("Great barracuda", "Giant trevally", "Black seabream")),
    aes(label = fb_name, color = class2),
    vjust = "outward", hjust = "outward",
    min.segment.length = 0.5,
    nudge_y = 1, nudge_x = 0.3,
    show.legend = FALSE
  ) +
  geom_label_repel(
    data = subset(fishbase_data_gmm, fb_name %in% c("Common snook", "Yellowfin tuna", "Swordfish")),
    aes(label = fb_name, color = clas2),
    color = "goldenrod1",
    vjust = "outward", hjust = "outward",
    min.segment.length = 30,
    nudge_y = -0.5,
    show.legend = FALSE
  ) +
  geom_jitter(aes(color = class2)) +
  ggtitle("Distribution of Scaled Species Movement Extents")

gmm_new_fig
#ggsave(gmm_new_fig, file = paste0("gmm_fig.png"), path = here::here("04_figs"), height = 8, width = 15)


# panel
gmm_panel <- ((dist_plot) | p1) / gmm_new_fig +
  plot_layout(heights = c(3,4)) &
  theme(plot.tag = element_text(face = "bold"))

gmm_panel
#ggsave(gmm_panel, file = paste0("gmm_panel.pdf"), path = here::here("04_figs", "final_figs"), height = 10, width = 15)

```


### Missing data figure

```{r}
missing <- miss_var_summary(fishbase_data)
missing2 <- miss_var_summary(filled_data)
missing3 <- miss_var_summary(filled_data2)

missing_fishbase_data <- fishbase_data %>% 
  dplyr::select(
    oxygen_cons, temp_range, dev_place, temp_min, temp_max,
    longevity_wild, temp_preferred, iucn_category, food_i,
  ) %>%
  rename(
    "Oxygen Consumption Rate" = oxygen_cons,
    "Temperature Range" = temp_range,
    "Place of Development" = dev_place,
    "Maximum Recorded Lifespan" = longevity_wild,
    "Optimal Temperature" = temp_preferred,
    "IUCN Category" = iucn_category,
    "Diet Items" = food_i,
    "Minimum Temperature" = temp_min,
    "Maximum Temperature" = temp_max,
  )

m1 <- gg_miss_var(missing_fishbase_data) +
  theme_bw(base_size = 16) +
  labs(y = "Missing Data Before Fills", x = "") +
  theme(axis.title.x = element_text(vjust = -1))
m1

missing_filled_data <- filled_data %>% 
  dplyr::select(
    oxygen_cons, temp_range, temp_min, temp_max,
    longevity_wild, temp_preferred, iucn_category, food_i,
  ) %>%
  rename(
    "Oxygen Consumption Rate" = oxygen_cons,
    "Temperature Range" = temp_range,
    "Maximum Recorded Lifespan" = longevity_wild,
    "Optimal Temperature" = temp_preferred,
    "IUCN Category" = iucn_category,
    "Diet Items" = food_i,
    "Minimum Temperature" = temp_min,
    "Maximum Temperature" = temp_max,
  )

m2 <- gg_miss_var(missing_filled_data) + # figure showing the missing data
  theme_bw(base_size = 16) +
  labs(y = "Missing Data After Genus-Level Fill", x = "Variable") +
  theme(axis.title.x = element_text(vjust = -1))
m2

missing_data <- filled_data2 %>%
  dplyr::select(
    oxygen_cons, temp_range, dev_place,
    longevity_wild, temp_preferred, iucn_category
  ) %>%
  rename(
    "Oxygen Consumption Rate" = oxygen_cons,
    "Temperature Range" = temp_range,
    "Place of Development" = dev_place,
    "Maximum Recorded Lifespan" = longevity_wild,
    "Optimal Temperature" = temp_preferred,
    "IUCN Category" = iucn_category
  )

m3 <- gg_miss_var(missing_data) +
  theme_bw(base_size = 16) +
  labs(y = "Missing Data After Family-Level Fill", x = "") +
  theme(axis.title.x = element_text(vjust = -1))
m3

missing_fig <- (m1 / m2 / m3) +
  plot_annotation(tag_levels = "A") &
  theme_bw(base_size = 16)
missing_fig

#ggsave(missing_fig, file = paste0("missing_data.pdf"), path = here::here("04_figs", "final_figs"), height = 12, width = 8)

```


### Individual Plots

```{r}
# continuous

plot_data <- filled_data2 %>%
  mutate(
    class2 = as.factor(class2),
    class3 = as.factor(class3),
    order = as.factor(order)
  )

response <- "class2"
expl_cont <- c(
  "temp_preferred", "fecundity_mean",
  "longevity_wild", "sp_richness", "length", "kfin",
  "r_fin", "diet_troph3", "oxygen_cons", "temp_range"
)

box_data <- function(x, y) {
  ggplot(plot_data, aes(x = .data[[y]], y = .data[[x]])) +
    geom_boxplot(aes(color = .data[[y]])) +
    theme_bw() +
    coord_flip() +
    labs(
      x = "Movement Class",
      color = "Class (Homerange/PLD)"
    ) +
    scale_color_viridis_d()
}

# plots_cont <- map(expl_cont, ~ box_data(.x, "class2"))
# plots_cont
```

```{r}

# significant panel
temp_plot <- box_data(x = "temp_preferred", y = "class2") +
  labs(y = "Optimal Temperature (ºC)", x = "") +
  scale_x_discrete(position = "top") +
  theme(axis.text.y = element_blank())
length_plot <- box_data(x = "length", y = "class2") +
  labs(y = "Length (cm)", x = "") +
  scale_x_discrete(position = "top")
long_plot <- box_data(x = "longevity_wild", y = "class2") +
  labs(y = "Maximum Lifespan (years)", x = "") +
  scale_x_discrete(position = "top")
diet_plot <- box_data(x = "diet_troph3", y = "class2") + 
  labs(y = "Trophic Level", x = "") +
  scale_x_discrete(position = "top") +
  theme(axis.text.y = element_blank())


kfin_plot <- box_data(x = "kfin", y = "class2") + 
  labs(y = "Carrying Capacity", x = "Movement Class") +
  scale_x_discrete(position = "top") +
  theme(axis.title.x = element_text(vjust = 0))
r_fin_plot <- box_data(x = "r_fin", y = "class2") + stat_kruskal_test(label.y = 1, label.x = 6, position = "jitter") +
  labs(y = "Growth Rate", x = "Movement Class")
oxygen_plot <- box_data(x = "oxygen_cons", y = "class2") + stat_kruskal_test(label.y = 2000, label.x = 6, position = "jitter") +
  labs(y = "Oxygen Consumption", x = "Movement Class")
temp_range_plot <- box_data(x = "temp_range", y = "class2") + stat_kruskal_test(label.y = 20, label.x = 3.5, position = "jitter") +
  labs(y = "Temperature Range", x = "Movement Class") + theme(axis.title.y = element_blank(), axis.text.y = element_blank())
fecund_plot <- box_data(x = "fecundity_mean", y = "class2") + stat_kruskal_test(label.y = 1000000, label.x = 5.5, position = "jitter") +
  labs(y = "Mean Fecundity", x = "Movement Class")
sp_rich_plot <- box_data(x = "sp_richness", y = "class2") + stat_kruskal_test(label.y = 1100, position = "jitter") +
  labs(y = "Species Richness", x = "Movement Class") + theme(axis.title.y = element_blank(), axis.text.y = element_blank())


numeric_panel <- ((temp_plot | length_plot) /
  (long_plot | diet_plot) /
  (r_fin_plot | kfin_plot) /
  (fecund_plot | sp_rich_plot) /
  (oxygen_plot | temp_range_plot)) +
  plot_layout(guides = "collect") + plot_annotation(tag_levels = "A")

numeric_panel
# ggsave(numeric_panel, file = paste0("numeric_panel.png"), path = here::here("04_figs", "individual_plots", "numeric"), height = 21, width = 14)

ind_panel <- ((temp_plot | length_plot) / (diet_plot | long_plot)) +
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") &
  theme(text = element_text(size = 14), legend.position = "none")

individual_panel <- wrap_elements(ind_panel) +
  labs(tag = "Movement Cohort") +
  theme(
    plot.tag = element_text(size = 14, angle = 270),
    plot.tag.position = "right"
  )

individual_panel

#ggsave(individual_panel, file = paste0("4_trait_panel.pdf"), path = here::here("04_figs", "final_figs"), height = 8, width = 13)

```


```{r}
ggsave(temp_plot, file = paste0("temp_plot.png"), path = here::here("04_figs", "individual_plots", "numeric"), height = 10, width = 10)
ggsave(fecund_plot, file = paste0("fecund_plot.png"), path = here::here("04_figs", "individual_plots", "numeric"), height = 10, width = 10)
ggsave(long_plot, file = paste0("long_plot.png"), path = here::here("04_figs", "individual_plots", "numeric"), height = 10, width = 10)
ggsave(sp_rich_plot, file = paste0("sp_rich_plot.png"), path = here::here("04_figs", "individual_plots", "numeric"), height = 10, width = 10)
ggsave(length_plot, file = paste0("length_plot.png"), path = here::here("04_figs", "individual_plots", "numeric"), height = 10, width = 10)
ggsave(kfin_plot, file = paste0("kfin_plot.png"), path = here::here("04_figs", "individual_plots", "numeric"), height = 10, width = 10)
ggsave(r_fin_plot, file = paste0("r_fin_plot.png"), path = here::here("04_figs", "individual_plots", "numeric"), height = 10, width = 10)
ggsave(diet_plot, file = paste0("diet_plot.png"), path = here::here("04_figs", "individual_plots", "numeric"), height = 10, width = 10)
ggsave(oxygen_plot, file = paste0("oxygen_plot.png"), path = here::here("04_figs", "individual_plots", "numeric"), height = 10, width = 10)
ggsave(temp_range_plot, file = paste0("temp_range_plot.png"), path = here::here("04_figs", "individual_plots", "numeric"), height = 10, width = 10)
```



```{r}
# categorical

expl_cat <- c(
  "climate", "body_shape_i", "dev_place", "movement_keyword",
  "demers_pelag", "iucn_category",
  "circadian", "food_mode", "ocean", "basin"
)

scatter_data <- function(x, y) {
  ggplot(plot_data, aes(x = .data[[x]], y = .data[[y]])) +
    geom_jitter(aes(color = .data[[y]])) +
    theme_bw() +
    labs(
      y = "Movement Class",
      color = "Class (homerange/PLD)"
    ) +
    scale_color_viridis_d() +
    theme(axis.text.x = element_text(angle = 40, hjust = 1))
}

# plots_cat <- map(expl_cat, ~ scatter_data(.x, "class2"))
# plots_cat
```

```{r}
body_plot <- scatter_data(x = "body_shape_i", y = "class2")
dev_plot <- scatter_data(x = "dev_place", y = "class2")
movement_plot <- scatter_data(x = "movement_keyword", y = "class2")
demers_plot <- scatter_data(x = "demers_pelag", y = "class2")
iucn_plot <- scatter_data(x = "iucn_category", y = "class2")
food_plot <- scatter_data(x = "food_mode", y = "class2")


ggsave(climate_plot, file = paste0("climate_plot.png"), path = here::here("04_figs", "individual_plots", "categorical"), height = 10, width = 10)
ggsave(body_plot, file = paste0("body_plot.png"), path = here::here("04_figs", "individual_plots", "categorical"), height = 10, width = 10)
ggsave(dev_plot, file = paste0("dev_plot.png"), path = here::here("04_figs", "individual_plots", "categorical"), height = 10, width = 10)
ggsave(movement_plot, file = paste0("movement_plot.png"), path = here::here("04_figs", "individual_plots", "categorical"), height = 10, width = 10)
ggsave(demers_plot, file = paste0("demers_plot.png"), path = here::here("04_figs", "individual_plots", "categorical"), height = 10, width = 10)
ggsave(iucn_plot, file = paste0("iucn_plot.png"), path = here::here("04_figs", "individual_plots", "categorical"), height = 10, width = 10)
ggsave(food_plot, file = paste0("food_plot.png"), path = here::here("04_figs", "individual_plots", "categorical"), height = 10, width = 10)
```
