---
title: "More Fishbase/Data"
author: "Lex Rosenberg"
date: "2023-06-30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(rfishbase)
library(naniar)
library(car)
library(sf)
library(sp)
library(ggpubr)
library(rstatix)
library(FSA)

```

### Load data

```{r}
filled_data2 <- read_csv(here::here("01_data", "02_processed_data", "filled_data2.csv")) %>%
  mutate_if(is.character, as.factor)

```

### Fill IUCN codes

```{r}

codes <- read_csv(here::here("01_data", "02_processed_data", "iucn_codes.csv"))

filled_data2 <- filled_data2 %>%
  left_join(codes, by = "species") %>%
  mutate(iucn_category = coalesce(iucn_category.x, iucn_category.y)) %>%
  dplyr::select(-iucn_category.x, -iucn_category.y)

```

### Consolidate and clean development variable

```{r}

filled_data2 <- filled_data2 %>% 
   mutate(dev_place = case_when(
    dev_place == "2002-03-26T00:00:00Z" ~ NA,
    dev_place != "planktonic" ~ "non-planktonic",
    TRUE ~ dev_place
   ))

```

### New missing fig

```{r}

missing <- miss_var_summary(filled_data2)

missing_data <- filled_data2 %>%
  dplyr::select(
    oxygen_cons, temp_range, basin, dev_place,
    longevity_wild, temp_preferred, iucn_category
  )

missing_filled_fig3 <- gg_miss_var(missing_data) + # figure showing the missing data
  theme_bw()
missing_filled_fig3

ggsave(missing_filled_fig3, file = paste0("missing_filled_fig3.png"), path = here::here("04_figs", "missing_data"))

```

```{r}

#write_csv(filled_data2, here::here("01_data", "02_processed_data", "filled_data2.csv"))

```

### Plot of newest clusters

```{r}

fishbase_data_gmm <- filled_data2 %>%
  mutate(class2 = as.factor(class2))

gmm_new_fig <- ggplot(fishbase_data_gmm, aes(magnitude_homerange, month_pld)) +
  geom_jitter(aes(color = class2)) +
  theme_bw(base_size = 20) +
  labs(
    x = "Order of Magnitude of Predicted Home Range",
    y = "Predicted Pelagic Larval Duration (Month)",
    color = "Class (homerange/PLD)"
  )

gmm_new_fig

# ggsave(gmm_new_fig, file = paste0("gmm_fig.pdf"), path = here::here("04_figs"), height = 8, width = 15)

```










### OLD


```{r}

# filled_data2 <- filled_data2 %>%
#   mutate(climate = tolower(climate)) %>%
#   mutate(climate = map(str_split(climate, boundary("word")), unique)) %>%  #remove repeated words
#   mutate(climate = as.character(climate))
# 
# filled_data2$climate <- gsub("^c","", filled_data2$climate) #remove c("")
# filled_data2$climate <- gsub("[()\"]","", filled_data2$climate)
# 
# 
# filled_data2 <- filled_data2 %>%
#   mutate(climate = as.factor(climate)) %>% 
#   mutate(climate = case_when(
#     climate == "subtropical, temperate, tropical" ~ "multiple",
#     climate == "boreal, subtropical, temperate" ~ "multiple",
#     climate == "boreal, polar, subtropical, temperate, tropical" ~ "multiple",
#     climate == "boreal, polar, subtropical, temperate" ~ "multiple",
#     climate == "tropical" ~ "warm_water",
#     climate == "polar, subtropical, tropical" ~ "multiple",
#     climate == "subtropical" ~ "warm_water",
#     climate == "boreal, polar, subtropical" ~ "multiple",
#     climate == "subtropical, tropical" ~ "warm_water",
#     climate == "polar, subtropical, temperate, tropical" ~ "multiple",
#     climate == "subtropical, temperate" ~ "multiple",
#     climate == "polar, subtropical, temperate" ~ "multiple",
#     climate == "boreal, subtropical, temperate, tropical" ~ "multiple",
#     climate == "polar, tropical" ~ "multiple",
#     climate == "temperate, tropical" ~ "multiple",
#     climate == "boreal, polar" ~ "multiple",
#     ))
# 
# # check climate groups with temp_preferred
# climate_temp_sum <- filled_data2 %>% 
#   select(species, climate, temp_preferred, temp_range, class2) %>%
#   filter(!is.na(temp_preferred)) %>% 
#   group_by(climate) %>% 
#   summarise(avg_temp = mean(temp_preferred), min_temp = min(temp_preferred), max_temp = max(temp_preferred)) %>% 
#   ungroup()

```




