---
title: "Geographic Processing"
author: "Allie Caughman"
date: "2023-05-23"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(sf)
library(sp)
```

```{r}
filled_data2 <- read_csv(here::here("01_data", "02_processed_data", "filled_data2.csv")) %>% 
  mutate_if(is.character, as.factor)

fish1 = st_read(here::here("01_data", "fish_ranges", "MARINEFISH", "MARINEFISH_PART1.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish2 = st_read(here::here("01_data", "fish_ranges", "MARINEFISH", "MARINEFISH_PART2.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish3 = st_read(here::here("01_data", "fish_ranges", "MARINEFISH", "MARINEFISH_PART3.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish4 = st_read(here::here("01_data", "fish_ranges", "ANGELFISH", "ANGELFISH.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish6 = st_read(here::here("01_data", "fish_ranges", "BONEFISH_TARPONS", "BONEFISH_TARPONS.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish8 = st_read(here::here("01_data", "fish_ranges", "CLUPEIFORMES", "CLUPEIFORMES.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish9 = st_read(here::here("01_data", "fish_ranges", "GROUPERS", "GROUPERS.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish10 = st_read(here::here("01_data", "fish_ranges", "HAGFISH", "HAGFISH.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish12 = st_read(here::here("01_data", "fish_ranges", "SEABREAMS_PORGIES_PICARELS", "SEABREAMS_PORGIES_PICARELS.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish13 = st_read(here::here("01_data", "fish_ranges", "SHARKS_RAYS_CHIMAERAS", "SHARKS_RAYS_CHIMAERAS.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish14 = st_read(here::here("01_data", "fish_ranges", "SURGEONFISHES_TANGS_UNICORNFISHES", "SURGEONFISHES_TANGS_UNICORNFISHES.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish15 = st_read(here::here("01_data", "fish_ranges", "SYNGNATHIFORM_FISHES", "SYNGNATHIFORM_FISHES.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish16 = st_read(here::here("01_data", "fish_ranges", "TUNAS_BILLFISHES", "TUNAS_BILLFISHES.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)
fish17 = st_read(here::here("01_data", "fish_ranges", "WRASSES_PARROTFISHES", "WRASSES_PARROTFISHES.shp")) %>% 
  filter(sci_name %in% filled_data2$species) %>% 
  rename(species = sci_name) %>% 
  select(species, geometry)

fish = list(fish1, fish2, fish3, fish4, 
            fish6, fish8, fish9, fish10) %>% 
  reduce(rbind) 

rm(fish1, fish2, fish3, fish4,
   fish6, fish8, fish9, fish10)

fish_2 = list(fish12, fish13, fish14, fish15,
            fish16, fish17) %>% 
  reduce(rbind)

rm(fish12, fish13, fish14, fish15, fish16, fish17)

fish = rbind(fish, fish_2)

rm(fish_2)

fish = fish %>% 
  mutate(present = "yes")

data = full_join(filled_data2, fish) %>% 
  distinct()

check = data %>% 
  select(-geometry) %>% 
  filter(is.na(present)) %>% 
  group_by(family) %>% 
  summarize(count = n())
```

```{r}
st_write(data, here::here("01_data", "02_processed_data", "fish_distributions.shp"))
```

```{r}
indian = st_read(here::here("01_data", "02_processed_data", "indian_intersection.shp")) %>% 
  mutate(ocean = "indian",
         basin = NA) %>% 
  select(species, ocean, basin)
artic = st_read(here::here("01_data", "02_processed_data", "artic_intersection.shp")) %>% 
  mutate(ocean = "artic",
         basin = NA) %>% 
  select(species, ocean, basin)
east_atlantic = st_read(here::here("01_data", "02_processed_data", "east_atlantic_intersection.shp")) %>% 
  mutate(ocean = "atlantic",
         basin = "east") %>% 
  select(species, ocean, basin)
east_pacific = st_read(here::here("01_data", "02_processed_data", "east_pacific_intersection.shp")) %>% 
  mutate(ocean = "pacific",
         basin = "east") %>% 
  select(species, ocean, basin)
west_atlantic = st_read(here::here("01_data", "02_processed_data", "west_atlantic_intersection.shp")) %>% 
  mutate(ocean = "atlantic",
         basin = "west") %>% 
  select(species, ocean, basin)
west_pacific = st_read(here::here("01_data", "02_processed_data", "west_pacific_intersection.shp")) %>% 
  mutate(ocean = "pacific",
         basin = "west") %>% 
  select(species, ocean, basin)

oceans = list(indian, artic, east_atlantic, east_pacific, west_atlantic, west_pacific) %>% 
  reduce(rbind) %>% 
  select(species, ocean, basin) %>% 
  as.data.frame()
```

```{r}
write_csv(oceans, here::here("01_data", "02_processed_data", "ocean_data.csv"))
```

