---
title: "PCA"
output: html_document
date: "2023-04-13"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(rfishbase)
library(FactoMineR)
library(factoextra)
library(vcd)

```


### Load and clean data

```{r}
fishbase_data <- read_csv(here::here("01_data", "02_processed_data", "fishbase_data.csv"))
fishbase_data[fishbase_data == "pelagic-oceanic"] <- "pelagic_oceanic"
fishbase_data[fishbase_data == "pelagic-neritic"] <- "pelagic_neritic"
fishbase_data[fishbase_data == "pelagic"] <- "pelagic_oceanic"
```


### Plot data

```{r}
#continuous 

plot1_data = fishbase_data 

#option1 sort by variable
plot1_data = plot1_data %>% 
  select(r_fin, species, class2) %>% 
  mutate(r_fin = sort(r_fin)) %>% 
  mutate(species = as.factor(species)) %>% 
  mutate(class2 = as.factor(class2)) %>% 
  mutate(species = fct_relevel(plot1_data$species))

ggplot(plot1_data, aes(species, r_fin)) +
  geom_point(aes(color = class2))

plot1_data = fishbase_data 

#option 2 sort by class
plot1_data = plot1_data %>% 
  select(r_fin, species, class2)%>% 
  mutate(class2 = sort(class2)) %>% 
  mutate(species = as.factor(species)) %>% 
  mutate(class2 = as.factor(class2)) %>% 
  mutate(species = fct_relevel(plot1_data$species))

#more descriptive****
ggplot(plot1_data, aes(r_fin, class2)) +
  geom_point(aes(color = r_fin))

#more to find groupings
ggplot(plot1_data, aes(species, r_fin)) +
  geom_point(aes(color = class2))
```

```{r}
#categorical
plot2_data = fishbase_data %>% 
  select(demers_pelag, r_fin, species, class2, family, 
         order, class_taxon, longevity_wild, diet_troph3) %>% 
  mutate(class2 = as.factor(class2), order = as.factor(order))

#to find groupings
ggplot(plot2_data, aes(demers_pelag, species)) +
  geom_point(aes(color = class2)) 

#more descriptive***
ggplot(plot2_data, aes(r_fin, class2)) +
  # geom_point(aes(color = demers_pelag)) +
  geom_jitter(aes(color = order)) +
  theme_bw() +
  labs(x = "Growth Rate",
       y = "Movement Class") +
  theme(legend.position = "none") +
  scale_color_viridis_d() +
  theme(axis.text.x = element_text(angle = 30, hjust=1)) 
  #scale_color_manual(values = c("", ""))
```


### Metabolic data

```{r}

plot2_data = fishbase_data
plot2_data <- plot2_data[!is.na(plot2_data$oxygen_cons),]

#option1 sort by oxygen_cons
plot2_data = plot2_data %>% 
  select(oxygen_cons, species, class2, genus) %>% 
  mutate(oxygen_cons = sort(oxygen_cons)) %>% 
  mutate(species = as.factor(species)) %>% 
  mutate(genus = as.factor(genus)) %>% 
  mutate(species = fct_relevel(plot2_data$species))

ggplot(plot2_data, aes(species, oxygen_cons)) +
  geom_point(aes(color = genus)) +
  theme_bw() +
  theme(legend.position="none") +
  theme(axis.text.x=element_blank()) +
  labs(x = "Species",
       y = "O2 Consumption Rate") +
  scale_color_viridis_d()

# no noteworthy groupings for class - try coloring by genus/family/order
# COLORING BY GENUS GAVE PERFECT LOOKING GRAPH??


#option 2 sort by class
plot2_data = plot2_data %>% 
  select(oxygen_cons, species, class2, order)%>% 
  mutate(class2 = sort(class2)) %>% 
  mutate(species = as.factor(species)) %>% 
  mutate(class2 = as.factor(class2)) %>% 
  mutate(species = fct_relevel(plot2_data$species))

#more descriptive****
ggplot(plot2_data, aes(oxygen_cons, class2)) +
  geom_point(aes(color = order)) +
  theme_bw() +
  labs(x = "O2 Consumption Rate",
       y = "Movement Class") +
  theme(legend.position = "none")



```




```{r}
# 
# plot3_data = fishbase_data %>% 
#   select(demers_pelag, env_temp, body_shape_i, species, class, class2) %>% 
#   mutate(class = as.factor(class), class2 = as.factor(class2))
# 
# #to find groupings
# ggplot(plot3_data, aes(species, env_temp)) +
#   geom_point(aes(color = class2))
# 
# #more descriptive
# ggplot(plot3_data, aes(body_shape_i, class2)) +
#   geom_jitter(aes(color = body_shape_i)) +
#   theme_bw() +
#   labs(x = "env_temp",
#        y = "Movement Class",
#        color = "Habitat Type") +
#   scale_color_viridis_d() +
#   theme(axis.text.x = element_text(angle = 30, hjust=1)) 
#   #scale_color_manual(values = c("", ""))
# 
# plot4_data = fishbase_data %>% 
#   select(length, species, class2) %>% 
#   #mutate(class2 = sort(length)) %>% this line is causing problemssssss
#   mutate(species = as.factor(species)) %>% 
#   mutate(class2 = as.factor(class2)) %>% 
#   mutate(species = fct_relevel(plot4_data$species))
# 
# ggplot(plot4_data, aes(species, length)) +
#   geom_jitter(aes(color = class2))
# 

```



### PCA with new variables added

```{r}
fishbase_p1 <- fishbase_data %>% 
  select(where(is.numeric)) %>% 
  select(r_fin, longevity_wild, length, fecundity_mean, class2) %>% 
  mutate(class2 = as.factor(class2))

p1 <- PCA(fishbase_p1[,1:4], graph = FALSE) # runs the PCA on the first 4 columns (not class)
p1

eigen_p1 <- p1$eig
eigen_p1 # 69.07% variance explained by first 2 components

p1_fig <- fviz_pca_ind(p1, label = "none", habillage = fishbase_p1$class2, addEllipses = TRUE, 
                ellipse.level = 0.95) +
            theme_minimal()
p1_fig

ggsave(p1_fig, file = paste0("p1_fig.png"), path = here::here("04_figs", "current_pca_famd"))


# Vizualize variable contributions to components

fviz_pca_biplot(p1, repel = TRUE, label = "none", habillage = fishbase_p1$class2)


# Contributions of variables to PC1
p1_c1 <- fviz_contrib(p1, choice = "var", axes = 1, top = 10)

# Contributions of variables to PC2
p1_c2 <- fviz_contrib(p1, choice = "var", axes = 2, top = 10)

components_p1 <- gridExtra::grid.arrange(p1_c1, p1_c2, ncol = 2)


ggsave(components_p1, file = paste0("components_p1.png"), path = here::here("04_figs", "current_pca_famd"))

```



```{r}
fishbase_p2 <- fishbase_data %>% 
  select(where(is.numeric)) %>% 
  select(r_fin, length, diet_troph3, class2) %>% 
  mutate(class2 = as.factor(class2))

p2 <- PCA(fishbase_p2[,1:3], graph = FALSE) # runs the PCA on the first 4 columns (not class)
p2

eigen_p2 <- p2$eig
eigen_p2 # 74.71% of variance explained by first 2 components

p2_fig <- fviz_pca_ind(p2, label = "none", habillage = fishbase_p2$class2, addEllipses = TRUE, 
                ellipse.level = 0.95) +
            theme_minimal()
p2_fig

#ggsave(p2_fig, file = paste0("p2_fig.png"), path = here::here("04_figs"))

```



### FAMD with new variables added

```{r}

fishbase_f1 <- fishbase_data %>% 
   select(weight, env_temp, temp_preferred, fecundity_mean, r_fin, class2) %>% 
   mutate(class2 = as.factor(class2), 
          env_temp = as.factor(env_temp)) %>% 
   na.omit()
 
f1 <- FAMD(fishbase_f1[,1:5], graph=FALSE)
f1

eigen_f1 <- f1$eig
eigen_f1 # 42.11% of variance explained by first 2 components


f1_fig <- fviz_famd_ind(f1, label = "none", habillage = fishbase_f1$class2, addEllipses = TRUE, ellipse.level = 0.95) +
  theme_minimal()

f1_fig

# ggsave(f1_fig, file = paste0("f1_fig.png"), path = here::here("04_figs"))


```

```{r}

fishbase_f2 <- fishbase_data %>% 
   select(r_fin, weight, env_temp, temp_preferred, demers_pelag, 
          body_shape_i, fecundity_mean, class2) %>% 
   mutate(class2 = as.factor(class2), 
          env_temp = as.factor(env_temp),
          demers_pelag = as.factor(demers_pelag),
          body_shape_i = as.factor(body_shape_i)) %>% 
   na.omit()
 
f2 <- FAMD(fishbase_f2[,1:7], graph=FALSE)
f2

eigen_f2 <- f2$eig
eigen_f2 # 42.11% of variance explained by first 2 components


f2_fig <- fviz_famd_ind(f2, label = "none", habillage = fishbase_f2$class2, addEllipses = TRUE, ellipse.level = 0.95) +
  theme_minimal()

f2_fig

#ggsave(f2_fig, file = paste0("f1_fig.png"), path = here::here("04_figs"))


```


```{r}

fishbase_f3 <- fishbase_data %>% 
  select(length, diet_troph3, demers_pelag, order) %>% 
  mutate(order = as.factor(order), demers_pelag = as.factor(demers_pelag)) %>% 
  na.omit()

f3 <- FAMD(fishbase_f3[,1:3], graph=FALSE)
f3

eigen_f3 <- f3$eig
eigen_f3 # 30.38% of variance explained by first 2 components


f3_fig <- fviz_famd_ind(f3, label = "none", habillage = fishbase_f3$order, addEllipses = FALSE, ellipse.level = 0.95) +
  theme_minimal() +
  theme(legend.position = "none")
f3_fig 


#ggsave(f3_fig, file = paste0("f3_fig.png"), path = here::here("04_figs", "current_pca_famd"))

```






### Initial PCA and FAMD

```{r}
fishbase_pca1 <- fishbase_data %>% 
  select(where(is.numeric)) %>% 
  select(r_fin, kfin, length, diet_troph3, class) %>% 
  mutate(class = as.factor(class))

# this will only work if all variables are numeric
#cor.mat <- round(cor(fishbase_pca1),2) # nothing is highly correlated - good!
#cor.mat

pca1 <- PCA(fishbase_pca1[,1:4], graph = FALSE) # runs the PCA on the first 4 columns (not class)
pca1

eigen_pca1 <- pca1$eig # large eigenvalue (>1) for a component = it accounts for greater amt of variation than og components
eigen_pca1 # 66.4% of variance explained by first 2 components

fviz_screeplot(pca1, ncp=10) # scree plot shows eigenvalues/variances associated w components


plot(pca1, choix = "var") # this is the same plot as the original PCA code on line 31?


pca1_fig <- fviz_pca_ind(pca1, label = "none", habillage = fishbase_pca1$class, addEllipses = TRUE, 
                ellipse.level = 0.95) +
            theme_minimal()
pca1_fig

#ggsave(pca1_fig, file = paste0("pca1_fig.png"), path = here::here("04_figs"))

```


```{r}

fishbase_pca2 <- fishbase_data %>% 
  select(where(is.numeric)) %>% 
  select(r_fin, length, diet_troph3, class) %>% 
  mutate(class = as.factor(class))

pca2 <- PCA(fishbase_pca2[,1:3], graph = FALSE) # runs the PCA on the first 4 columns (not class)

eigen_pca2 <- pca2$eig # large eigenvalue (>1) for a component = it accounts for greater amt of variation than og components
eigen_pca2 # 81.45% of variance explained by first 2 components

plot(pca2, choix = "var")


pca2_fig <- fviz_pca_ind(pca2, label = "none", habillage = fishbase_pca2$class, addEllipses = TRUE, 
                ellipse.level = 0.95) +
            theme_minimal()
pca2_fig

#ggsave(pca2_fig, file = paste0("pca2_fig.png"), path = here::here("04_figs"))

```


```{r}

fishbase_pca3 <- fishbase_data %>% 
  select(where(is.numeric)) %>% 
  select(kfin, length, diet_troph3, class) %>% 
  mutate(class = as.factor(class))

pca3 <- PCA(fishbase_pca3[,1:3], graph = FALSE) # runs the PCA on the first 4 columns (not class)

eigen_pca3 <- pca3$eig # large eigenvalue (>1) for a component = it accounts for greater amt of variation than og components
eigen_pca3 # 81.29% of variance explained by first 2 components

plot(pca3, choix = "var")


pca3_fig <- fviz_pca_ind(pca3, label = "none", habillage = fishbase_pca3$class, addEllipses = TRUE, 
                ellipse.level = 0.95) +
            theme_minimal()
pca3_fig

#ggsave(pca3_fig, file = paste0("pca3_fig.png"), path = here::here("04_figs"))

```


```{r}

fishbase_pca4 <- fishbase_data %>% 
  select(where(is.numeric)) %>% 
  select(length, diet_troph3, class) %>% 
  mutate(class = as.factor(class))

pca4 <- PCA(fishbase_pca4[,1:2], graph = FALSE) # runs the PCA on the first 4 columns (not class)

eigen_pca4 <- pca4$eig # large eigenvalue (>1) for a component = it accounts for greater amt of variation than og components
eigen_pca4 # only 2 components

plot(pca4, choix = "var")


pca4_fig <- fviz_pca_ind(pca4, label = "none", habillage = fishbase_pca4$class, addEllipses = TRUE, 
                ellipse.level = 0.95) +
            theme_minimal()
pca4_fig # group 6 pretty clearly defined?

#ggsave(pca4_fig, file = paste0("pca4_fig.png"), path = here::here("04_figs"))

```


### FAMD

```{r}

fishbase_famd1 <- fishbase_data %>% 
  select(r_fin, kfin, length, diet_troph3, movement_keyword, food_i, class) %>% 
  mutate(class = as.factor(class), movement_keyword = as.factor(movement_keyword), food_i = as.factor(food_i)) %>% 
  na.omit(fishbase_famd1)


famd1 <- FAMD(fishbase_famd1[,1:6], graph=FALSE)
famd1

eigen_famd1 <- famd1$eig
eigen_famd1 # 7.23% of variance explained by first 2 components!?


famd1_fig <- fviz_famd_ind(famd1, label = "none", habillage = fishbase_famd1$class, addEllipses = TRUE, ellipse.level = 0.95) +
  theme_minimal()

famd1_fig
#ggsave(famd1_fig, file = paste0("famd1_fig.png"), path = here::here("04_figs"))


```


```{r}

fishbase_famd2 <- fishbase_data %>% 
  select(length, food_i, class) %>% 
  mutate(class = as.factor(class), food_i = as.factor(food_i)) %>% 
  na.omit(fishbase_famd2)

famd2 <- FAMD(fishbase_famd2[,1:2], graph=FALSE)

eigen_famd2 <- famd2$eig
eigen_famd2 # 5.49% 


famd2_fig <- fviz_famd_ind(famd2, label = "none", habillage = fishbase_famd2$class, addEllipses = TRUE, ellipse.level = 0.95) +
  theme_minimal()

famd2_fig
#ggsave(famd2_fig, file = paste0("famd2_fig.png"), path = here::here("04_figs"))


```


```{r}

fishbase_famd3 <- fishbase_data %>% 
  select(r_fin, kfin, diet_troph3, iucn_category, class) %>% 
  mutate(class = as.factor(class), iucn_category = as.factor(iucn_category)) %>% 
  na.omit(fishbase_famd3)

famd3 <- FAMD(fishbase_famd3[,1:4], graph=FALSE)
famd3

eigen_famd3 <- famd3$eig
eigen_famd3 # 31.50% of variance explained by first 2 components


famd3_fig <- fviz_famd_ind(famd3, label = "none", habillage = fishbase_famd3$class, addEllipses = TRUE, ellipse.level = 0.95) +
  theme_minimal()

famd3_fig 
#ggsave(famd3_fig, file = paste0("famd3_fig.png"), path = here::here("04_figs"))


```


```{r}

fishbase_famd4 <- fishbase_data %>% 
  select(length, iucn_category, class) %>% 
  mutate(class = as.factor(class), iucn_category = as.factor(iucn_category)) %>% 
  na.omit(fishbase_famd4)

famd4 <- FAMD(fishbase_famd4[,1:2], graph=FALSE)
famd4

eigen_famd4 <- famd4$eig
eigen_famd4 # 38.75% of variance explained by first 2 components


famd4_fig <- fviz_famd_ind(famd4, label = "none", habillage = fishbase_famd4$class, addEllipses = TRUE, ellipse.level = 0.95) +
  theme_minimal()

famd4_fig
#ggsave(famd4_fig, file = paste0("famd4_fig.png"), path = here::here("04_figs"))


```


```{r}

fishbase_famd5 <- fishbase_data %>% 
  select(length, demers_pelag, diet_troph3, class) %>% 
  mutate(class = as.factor(class), 
         demers_pelag = as.factor(demers_pelag), 
         diet_troph3 = as.factor(diet_troph3)) %>% 
  na.omit(fishbase_famd5)

famd5 <- FAMD(fishbase_famd5[,1:3], graph=FALSE)
famd5

eigen_famd5 <- famd5$eig
eigen_famd5 # 1.27% of variance explained by first 2 components!?


famd5_fig <- fviz_famd_ind(famd5, label = "none", habillage = fishbase_famd5$class, addEllipses = TRUE, ellipse.level = 0.95) +
  theme_minimal()
famd5_fig

ggsave(famd5_fig, file = paste0("famd5_fig.png"), path = here::here("04_figs"))

```


```{r}

fishbase_famd6 <- fishbase_data %>% 
  select(length, diet_troph3, demers_pelag, class) %>% 
  mutate(class = as.factor(class), demers_pelag = as.factor(demers_pelag)) %>% 
  na.omit()

famd6 <- FAMD(fishbase_famd6[,1:3], graph=FALSE)
famd6

eigen_famd6 <- famd6$eig
eigen_famd6 # 30.38% of variance explained by first 2 components


famd6_fig <- fviz_famd_ind(famd6, label = "none", habillage = fishbase_famd6$class, addEllipses = TRUE, ellipse.level = 0.95) +
  theme_minimal()
famd6_fig # still pretty good groupings here

famd6_1_fig <- fviz_famd_ind(famd6, label = "none", habillage = fishbase_famd6$class) +
  theme_minimal()
famd6_1_fig # really interesting.. what does it mean?


#ggsave(famd6_fig, file = paste0("famd6_fig.png"), path = here::here("04_figs"))
#ggsave(famd6_1_fig, file = paste0("famd6_1_fig.png"), path = here::here("04_figs"))

```






### Old


```{r}
# 
# fishbase_famd5 <- fishbase_data %>% 
#   select(r_fin, kfin, length, diet_troph3, movement_keyword, demers_pelag, food_i, class) %>% 
#   mutate(class = as.factor(class), 
#          movement_keyword = as.factor(movement_keyword), 
#          food_i = as.factor(food_i), 
#          demers_pelag = as.factor(demers_pelag)) %>%  # error here?  <--------------------------------------------
#   na.omit(fishbase_famd5)
#   
# 
# famd5 <- FAMD(fishbase_famd5[,1:7], graph=FALSE)
# famd5
# 
# eigen_famd5 <- famd5$eig
# eigen_famd5 # 7.23% of variance explained by first 2 components!?
# 
# 
# famd5_fig <- fviz_famd_ind(famd5, label = "none", habillage = fishbase_famd5$class, addEllipses = TRUE, ellipse.level = 0.95) +
#   theme_minimal()
# 
# famd5_fig
# #ggsave(famd5_fig, file = paste0("famd5_fig.png"), path = here::here("04_figs"))
# 

```


```{r}
# 
# fishbase_famd5 <- fishbase_data %>% 
#   select(r_fin, kfin, length, diet_troph3, food_i, movement_keyword, iucn_category, demers_pelag, class) %>% 
#   mutate(class = as.factor(class), 
#          demers_pelag = as.factor(demers_pelag), 
#          iucn_category = as.factor(iucn_category), 
#          food_i = as.factor(food_i), 
#          movement_keyword = as.factor(movement_keyword)) %>% 
#   na.omit(fishbase_famd5) # error why?  <------------------------------------------------------------------
# 
# famd5 <- FAMD(fishbase_famd5[,1:8], graph=FALSE)
# famd5
# 
# eigen_famd5 <- famd5$eig
# eigen_famd5 # 30.38% of variance explained by first 2 components
# 
# 
# famd5_fig <- fviz_famd_ind(famd5, label = "none", habillage = fishbase_famd5$class, addEllipses = TRUE, ellipse.level = 0.95) +
#   theme_minimal()
# famd5_fig 
# 
# 
# #ggsave(famd5_fig, file = paste0("famd5_fig.png"), path = here::here("04_figs"))
# 

```
