---
title: "PCA"
output: pdf_document
date: "2023-04-13"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(rfishbase)
library(FactoMineR)
library(factoextra)
library(vcd)
library(purrr)
library(car)
library(vegan)
library(patchwork)
```

### Load data

```{r}
filled_data <- read_csv(here::here("01_data", "02_processed_data", "filled_data2.csv")) %>%
  mutate_if(is.character, as.factor)
```

### Run nMDS and FAMD


#### FAMD

```{r}
famd_filled <- filled_data %>%
  dplyr::select(
    temp_preferred, 
    fecundity_mean, 
    longevity_wild,
    sp_richness, 
    length, 
    kfin, 
    r_fin, 
    diet_troph3, 
    climate, 
    body_shape_i, 
    dev_place,
    demers_pelag,
    iucn_category, 
    oxygen_cons, 
    temp_range,
    food_mode, class2
  ) %>%
  mutate(class2 = as.factor(class2)) %>%
  na.omit()


f1 <- FAMD(famd_filled[, 1:15], graph = FALSE)
f1

# Contribution to the first dimension
fviz_contrib(f1, "var", axes = 1) + fviz_contrib(f1, "var", axes = 2)


# PLOTS ARROWS
p1 <- fviz_famd_var(f1, "quanti.var",
  repel = TRUE,
  col.var = "black"
)

eigen_f1 <- f1$eig
eigen_f1 # only 8% of variance explained by first 2 components......


f1_fig <- fviz_famd_ind(f1, label = "none", habillage = famd_filled$class2, addEllipses = TRUE, ellipse.level = 0.95, invisible = "quali.var") +
  theme_bw() +
  scale_color_viridis_d() +
  scale_fill_viridis_d()

plot1 <- p1 + f1_fig

plot1

f1_fig_2 <- fviz_famd_ind(f1, label = "none", habillage = famd_filled$class2, addEllipses = TRUE, ellipse.level = 0.5, invisible = "quali.var") +
  theme_bw() +
  scale_color_viridis_d() +
  scale_fill_viridis_d()

f1_fig_2

# ggsave(plot1, file = paste0("f1.png"), path = here::here("04_figs", "famd_with_arrows"))
```

```{r}
famd_filled <- filled_data %>%
  dplyr::select(
    temp_preferred, 
    #fecundity_mean, 
    longevity_wild,
    sp_richness, 
    length, 
    #kfin, 
    r_fin, 
    diet_troph3, 
    climate, 
    #body_shape_i, 
    #dev_place,
    demers_pelag,
    iucn_category, 
    oxygen_cons, 
    temp_range,
    #food_mode, 
    class2
  ) %>%
  mutate(class2 = as.factor(class2)) %>%
  na.omit()


f2 <- FAMD(famd_filled[, 1:11], graph = FALSE)
f2

# Contribution to the first dimension
fviz_contrib(f2, "var", axes = 1) + fviz_contrib(f2, "var", axes = 2)
# Contribution to the second dimensio

# PLOTS ARROWS
p2 <- fviz_famd_var(f2, "quanti.var",
  repel = TRUE,
  col.var = "black"
)

eigen_f2 <- f2$eig
eigen_f2 # only 8% of variance explained by first 2 components......


f2_fig <- fviz_famd_ind(f2, label = "none", habillage = famd_filled$class2, addEllipses = TRUE, ellipse.level = 0.95, invisible = "quali.var") +
  theme_bw() +
  scale_color_viridis_d()+
  scale_fill_viridis_d()

plot2 <- p2 + f2_fig

plot2

f2_fig_2 <- fviz_famd_ind(f2, label = "none", habillage = famd_filled$class2, addEllipses = TRUE, ellipse.level = 0.5, invisible = "quali.var") +
  theme_bw() +
  scale_color_viridis_d()+
  scale_fill_viridis_d()

f2_fig_2

# ggsave(plot2, file = paste0("f2.png"), path = here::here("04_figs", "famd_with_arrows"))
```

```{r}
famd_filled <- filled_data %>%
  dplyr::select(
    temp_preferred, 
    #fecundity_mean, 
    longevity_wild,
    sp_richness, 
    length, 
    #kfin, 
    r_fin, 
    diet_troph3, 
    climate, 
    #body_shape_i, 
    #dev_place,
    demers_pelag,
    iucn_category, 
    oxygen_cons, 
    #temp_range,
    #food_mode, 
    class2
  ) %>%
  mutate(class2 = as.factor(class2)) %>%
  na.omit()


f3 <- FAMD(famd_filled[, 1:10], graph = FALSE)
f3

# Contribution to the first dimension
fviz_contrib(f3, "var", axes = 1) + fviz_contrib(f3, "var", axes = 2)
# Contribution to the second dimension

# PLOTS ARROWS
p3 <- fviz_famd_var(f3, "quanti.var",
  repel = TRUE,
  col.var = "black"
)

eigen_f3 <- f3$eig
eigen_f3 # only 8% of variance explained by first 2 components......


f3_fig <- fviz_famd_ind(f3, label = "none", habillage = famd_filled$class2, addEllipses = TRUE, ellipse.level = 0.95, invisible = "quali.var") +
  theme_bw() +
  scale_color_viridis_d()+
  scale_fill_viridis_d()

plot3 <- p3 + f3_fig

plot3

f3_fig_2 <- fviz_famd_ind(f3, label = "none", habillage = famd_filled$class2, addEllipses = TRUE, ellipse.level = 0.5, invisible = "quali.var") +
  theme_bw() +
  scale_color_viridis_d()+
  scale_fill_viridis_d()

f3_fig_2
# ggsave(plot3, file = paste0("f3.png"), path = here::here("04_figs", "famd_with_arrows"))
```

#### NMDS Plot 1

```{r}
com_data <- filled_data %>%
  dplyr::select(
    temp_preferred, fecundity_mean, longevity_wild,
    sp_richness, length, kfin, r_fin, diet_troph3, oxygen_cons, 
    temp_range, species, order, class2
  ) %>%
  filter(temp_preferred > 0) %>%
  na.omit()

com <- com_data %>%
  dplyr::select(-species, -order, -class2)

m_com <- as.matrix(com) # make matrix from dataframe

set.seed(123)
nmds <- metaMDS(m_com, distance = "euclidean")
nmds # stress: 0.1716711, weak ties

# extract NMDS scores (x and y coordinates)
filled_scores <- as.data.frame(scores(nmds)$sites)

# add columns to data frame
filled_scores$class2 <- com_data$class2
filled_scores$species <- com_data$species
filled_scores$order <- com_data$order

filled_scores <- filled_scores %>%
  mutate(class2 = as.factor(class2), order = as.factor(order), species = as.factor(species))


species_scores <- as.data.frame(nmds[["species"]]) %>%
  rownames_to_column(var = "var")

mean = filled_scores %>% 
  group_by(class2) %>% 
  summarize(mean1 = mean(NMDS1),
            mean2 = mean(NMDS2))

nmds_plot1 <- ggplot(filled_scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = class2)) +
  labs(x = "NMDS1", y = "NMDS2") +
  stat_ellipse(geom = "polygon", aes(fill = class2, color = class2), alpha = 0.2, level = 0.95) +
  geom_segment(data = species_scores, aes(x = 0, xend = MDS1, y = 0, yend = MDS2), arrow = arrow(length = unit(0.25, "cm")), colour = "grey10", lwd = 0.3) +
  ggrepel::geom_text_repel(data = species_scores, aes(x = MDS1, y = MDS2, label = var), cex = 3, direction = "both", segment.size = 0.25) +
  geom_point(data = mean, aes(mean1, mean2, color = class2), size = 4) + 
  theme_bw() +
  scale_color_viridis_d() +
  scale_fill_viridis_d()


nmds_plot1

nmds_plot1.1 <- ggplot(filled_scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = class2)) +
  labs(x = "NMDS1", y = "NMDS2") +
  stat_ellipse(geom = "polygon", aes(fill = class2, color = class2), alpha = 0.2, level = 0.5) +
  geom_segment(data = species_scores, aes(x = 0, xend = MDS1, y = 0, yend = MDS2), arrow = arrow(length = unit(0.25, "cm")), colour = "grey10", lwd = 0.3) +
  ggrepel::geom_text_repel(data = species_scores, aes(x = MDS1, y = MDS2, label = var), cex = 3, direction = "both", segment.size = 0.25) +
  geom_point(data = mean, aes(mean1, mean2, color = class2), size = 4) + 
  theme_bw() +
  scale_color_viridis_d() +
  scale_fill_viridis_d()


nmds_plot1.1

# ggsave(nmds_plot1, file = paste0("nmds_plot1.png"), path = here::here("04_figs", "nmds"))
```


```{r}
com_data <- filled_data %>%
  dplyr::select(
    #temp_preferred, 
    fecundity_mean, 
    longevity_wild,
    #sp_richness, 
    #length, 
    kfin, 
    r_fin, 
    #diet_troph3, ,
    oxygen_cons, 
    #temp_range,
    species, order, class2
  ) %>%
  na.omit()

com <- com_data %>%
  dplyr::select(-species, -order, -class2)

m_com <- as.matrix(com) # make matrix from dataframe

set.seed(123)
nmds <- metaMDS(m_com, distance = "euclidean")
nmds # stress: 0.1716711, weak ties

# extract NMDS scores (x and y coordinates)
filled_scores <- as.data.frame(scores(nmds)$sites)

# add columns to data frame
filled_scores$class2 <- com_data$class2
filled_scores$species <- com_data$species
filled_scores$order <- com_data$order

filled_scores <- filled_scores %>%
  mutate(class2 = as.factor(class2), order = as.factor(order), species = as.factor(species))


species_scores <- as.data.frame(nmds[["species"]]) %>%
  rownames_to_column(var = "var")

mean = filled_scores %>% 
  group_by(class2) %>% 
  summarize(mean1 = mean(NMDS1),
            mean2 = mean(NMDS2))

nmds_plot2 <- ggplot(filled_scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = class2)) +
  labs(x = "NMDS1", y = "NMDS2") +
  stat_ellipse(geom = "polygon", aes(color = class2, fill = class2), alpha = 0.2, level = 0.95) +
  geom_segment(data = species_scores, aes(x = 0, xend = MDS1, y = 0, yend = MDS2), arrow = arrow(length = unit(0.25, "cm")), colour = "grey10", lwd = 0.3) +
  ggrepel::geom_text_repel(data = species_scores, aes(x = MDS1, y = MDS2, label = var), cex = 3, direction = "both", segment.size = 0.25) +
    geom_point(data = mean, aes(mean1, mean2, color = class2), size = 4) + 
  theme_bw() +
  scale_color_viridis_d() +
  scale_fill_viridis_d()


nmds_plot2 # classes 3 and 4 are distinct!
# coloring by order gave four plus distinct groups..?

nmds_plot2.1 <- ggplot(filled_scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = class2)) +
  labs(x = "NMDS1", y = "NMDS2") +
  stat_ellipse(geom = "polygon", aes(color = class2, fill = class2), alpha = 0.2, level = 0.5) +
  geom_segment(data = species_scores, aes(x = 0, xend = MDS1, y = 0, yend = MDS2), arrow = arrow(length = unit(0.25, "cm")), colour = "grey10", lwd = 0.3) +
  ggrepel::geom_text_repel(data = species_scores, aes(x = MDS1, y = MDS2, label = var), cex = 3, direction = "both", segment.size = 0.25) +
    geom_point(data = mean, aes(mean1, mean2, color = class2), size = 4) + 
  theme_bw() +
  scale_color_viridis_d() +
  scale_fill_viridis_d()


nmds_plot2.1

# ggsave(nmds_plot2, file = paste0("nmds_plot2.png"), path = here::here("04_figs", "nmds"))
```

```{r}
#at least one over 0.10
com_data <- filled_data %>%
  dplyr::select(
    #temp_preferred, 
    fecundity_mean, 
    longevity_wild,
    #sp_richness, 
    #length, 
    kfin, 
    #r_fin, 
    #diet_troph3, ,
    oxygen_cons, 
    #temp_range,
    species, order, class2
  ) %>%
  na.omit()

com <- com_data %>%
  dplyr::select(-species, -order, -class2)

m_com <- as.matrix(com) # make matrix from dataframe

set.seed(123)
nmds <- metaMDS(m_com, distance = "euclidean")
nmds # stress: 0.1716711, weak ties

# extract NMDS scores (x and y coordinates)
filled_scores <- as.data.frame(scores(nmds)$sites)

# add columns to data frame
filled_scores$class2 <- com_data$class2
filled_scores$species <- com_data$species
filled_scores$order <- com_data$order

filled_scores <- filled_scores %>%
  mutate(class2 = as.factor(class2), order = as.factor(order), species = as.factor(species))


species_scores <- as.data.frame(nmds[["species"]]) %>%
  rownames_to_column(var = "var")

mean = filled_scores %>% 
  group_by(class2) %>% 
  summarize(mean1 = mean(NMDS1),
            mean2 = mean(NMDS2))

nmds_plot3 <- ggplot(filled_scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = class2)) +
  labs(x = "NMDS1", y = "NMDS2") +
  stat_ellipse(geom = "polygon", aes(color = class2, fill = class2), alpha = 0.2, level = 0.95) +
  geom_segment(data = species_scores, aes(x = 0, xend = MDS1, y = 0, yend = MDS2), arrow = arrow(length = unit(0.25, "cm")), colour = "grey10", lwd = 0.3) +
  ggrepel::geom_text_repel(data = species_scores, aes(x = MDS1, y = MDS2, label = var), cex = 3, direction = "both", segment.size = 0.25) +
    geom_point(data = mean, aes(mean1, mean2, color = class2), size = 4) + 
  theme_bw() +
  scale_color_viridis_d() +
  scale_fill_viridis_d()


nmds_plot3 


nmds_plot3.1 <- ggplot(filled_scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = class2)) +
  labs(x = "NMDS1", y = "NMDS2") +
  stat_ellipse(geom = "polygon", aes(color = class2, fill = class2), alpha = 0.2, level = 0.5) +
  geom_segment(data = species_scores, aes(x = 0, xend = MDS1, y = 0, yend = MDS2), arrow = arrow(length = unit(0.25, "cm")), colour = "grey10", lwd = 0.3) +
  ggrepel::geom_text_repel(data = species_scores, aes(x = MDS1, y = MDS2, label = var), cex = 3, direction = "both", segment.size = 0.25) +
    geom_point(data = mean, aes(mean1, mean2, color = class2), size = 4) + 
  theme_bw() +
  scale_color_viridis_d() +
  scale_fill_viridis_d()


nmds_plot3.1

# ggsave(nmds_plot3, file = paste0("nmds_plot3.png"), path = here::here("04_figs", "nmds"))
```

