---
title: "More Fishbase/Data"
author: "Lex Rosenberg"
date: "2023-06-30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(rfishbase)
library(naniar)
library(car)
library(sf)
library(sp)
library(ggpubr)
library(rstatix)
library(FSA)
```

### Load data

```{r}
filled_data2 <- read_csv(here::here("01_data", "02_processed_data", "filled_data2.csv")) %>%
  mutate_if(is.character, as.factor)
```

### Fill IUCN codes

```{r}
codes <- read_csv(here::here("01_data", "02_processed_data", "iucn_codes.csv"))

filled_data2 <- filled_data2 %>%
  left_join(codes, by = "species") %>%
  mutate(iucn_category = coalesce(iucn_category.x, iucn_category.y)) %>%
  dplyr::select(-iucn_category.x, -iucn_category.y)
```

### Consolidate and clean development variable

```{r}
filled_data2 <- filled_data2 %>%
  mutate(dev_place = case_when(
    dev_place == "2002-03-26T00:00:00Z" ~ NA,
    dev_place != "planktonic" ~ "non-planktonic",
    TRUE ~ dev_place
  ))
```

# Add common names

```{r}
names <- species(fields = c("SpecCode", "FBname")) %>%
  filter(SpecCode %in% filled_data2$spec_code) %>%
  rename(fb_name = FBname, spec_code = SpecCode)

filled_data2 <- left_join(filled_data2, names)
```


```{r}
# write_csv(filled_data2, here::here("01_data", "02_processed_data", "filled_data2.csv"))
```









### OLD


```{r}
# filled_data2 <- filled_data2 %>%
#   mutate(climate = tolower(climate)) %>%
#   mutate(climate = map(str_split(climate, boundary("word")), unique)) %>%  #remove repeated words
#   mutate(climate = as.character(climate))
#
# filled_data2$climate <- gsub("^c","", filled_data2$climate) #remove c("")
# filled_data2$climate <- gsub("[()\"]","", filled_data2$climate)
#
#
# filled_data2 <- filled_data2 %>%
#   mutate(climate = as.factor(climate)) %>%
#   mutate(climate = case_when(
#     climate == "subtropical, temperate, tropical" ~ "multiple",
#     climate == "boreal, subtropical, temperate" ~ "multiple",
#     climate == "boreal, polar, subtropical, temperate, tropical" ~ "multiple",
#     climate == "boreal, polar, subtropical, temperate" ~ "multiple",
#     climate == "tropical" ~ "warm_water",
#     climate == "polar, subtropical, tropical" ~ "multiple",
#     climate == "subtropical" ~ "warm_water",
#     climate == "boreal, polar, subtropical" ~ "multiple",
#     climate == "subtropical, tropical" ~ "warm_water",
#     climate == "polar, subtropical, temperate, tropical" ~ "multiple",
#     climate == "subtropical, temperate" ~ "multiple",
#     climate == "polar, subtropical, temperate" ~ "multiple",
#     climate == "boreal, subtropical, temperate, tropical" ~ "multiple",
#     climate == "polar, tropical" ~ "multiple",
#     climate == "temperate, tropical" ~ "multiple",
#     climate == "boreal, polar" ~ "multiple",
#     ))
#
# # check climate groups with temp_preferred
# climate_temp_sum <- filled_data2 %>%
#   select(species, climate, temp_preferred, temp_range, class2) %>%
#   filter(!is.na(temp_preferred)) %>%
#   group_by(climate) %>%
#   summarise(avg_temp = mean(temp_preferred), min_temp = min(temp_preferred), max_temp = max(temp_preferred)) %>%
#   ungroup()
```
