---
title: "stats"
author: "Lex Rosenberg"
date: "2023-06-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(ggpubr)
library(effectsize)
library(rstatix)
library(FSA)
library(chisq.posthoc.test)
library(MASS)
library(sjPlot)
library(marginaleffects)
library(patchwork)
```

### Load data

```{r}
filled_data2 <- read_csv(here::here("01_data", "02_processed_data", "filled_data2.csv")) %>%
  mutate_if(is.character, as.factor)

```

### Characterize data

```{r}

# Cohort sample size
sample_size <- filled_data2 %>% 
  group_by(class2) %>% 
  summarise(n = length(class2))

# Trait means, medians, and sd by cohort
cohort_summary <- filled_data2 %>% 
  dplyr::select(class2, length, temp_preferred, longevity_wild, diet_troph3) %>% 
  group_by(class2) %>% 
  summarise(across(where(is.numeric), list(mean = mean, sd = sd, median = median), na.rm=TRUE))

```

### Build linear models

```{r}
lm1 <- lm(log(home_range) ~ length * diet_troph3 * longevity_wild * temp_preferred, data = filled_data2)
lm2 <- lm(pld ~ length * diet_troph3 * longevity_wild * temp_preferred, data = filled_data2)
stepAIC(lm1)
stepAIC(lm2)

lm1.1 <- lm(log(home_range) ~ length + diet_troph3 + longevity_wild +
  temp_preferred + length:diet_troph3 + length:longevity_wild +
  diet_troph3:longevity_wild + length:temp_preferred + diet_troph3:temp_preferred +
  longevity_wild:temp_preferred + length:diet_troph3:longevity_wild +
  length:diet_troph3:temp_preferred + length:longevity_wild:temp_preferred, data = filled_data2)
lm2.1 <- lm(
  pld ~ length + diet_troph3 + longevity_wild + temp_preferred +
    length:longevity_wild + length:temp_preferred + diet_troph3:temp_preferred +
    longevity_wild:temp_preferred + length:longevity_wild:temp_preferred,
  data = filled_data2
)

anova(lm1, lm1.1)
anova(lm2, lm2.1)

summary(lm1.1)
Anova(lm1.1, type = "III")

summary(lm2.1)
Anova(lm2.1, type = "III")

p1 <- plot_comparisons(lm1.1, variables = "temp_preferred", condition = c("length", "diet_troph3"), comparison = "difference") +
  labs(
    x = "Optimal Temperature (ºC)",
    y = "Home Range Difference with Length",
    color = "Trophic Level",
    fill = "Trophic Level",
  ) +
  theme_bw(base_size = 18) +
  scale_color_manual(values = c("#2a788e", "#355f8d", "#414487", "#482475", "#440154"),
                     name = "Trophic Level", labels = c("2.00", "3.48", "3.84", "4.21", "4.65")) +
  scale_fill_manual(values = c("#2a788e", "#355f8d", "#414487", "#482475", "#440154"), 
                    name = "Trophic Level", labels = c("2.00", "3.48", "3.84", "4.21", "4.65")) +
  xlim(NA, 45) + 
  ylim(-0.5, 0.5)
  
p2 <- plot_comparisons(lm1.1, variables = "temp_preferred", condition = list("length", "longevity_wild" = c(1, 10, 16, 25, 50, 100))) +
  labs(
    x = "Optimal Temperature (ºC)",
    y = "Home Range Difference with Length",
    color = "Maximum Lifespan (yr)",
    fill = "Maximum Lifespan (yr)"
  ) +
  theme_bw(base_size = 18) +
  scale_color_manual(values = c("#fde725", "#bddf26", "#7ad151", "#44bf70", "#22a884", "#21918c")) +
  scale_fill_manual(values = c("#fde725", "#bddf26", "#7ad151", "#44bf70", "#22a884", "#21918c")) +
  xlim(NA, 45) + 
  ylim(-0.25, 0.5)

p3 <- plot_comparisons(lm1.1, variables = "longevity_wild", condition = c("length", "diet_troph3"), comparison = "difference") +
  labs(
    x = "Maximum Lifespan (yr)",
    y = "Home Range Difference with Length",
    color = "Trophic Level",
    fill = "Trophic Level"
  ) +
  theme_bw(base_size = 18) +
  scale_color_manual(values = c("#2a788e", "#355f8d", "#414487", "#482475", "#440154"), 
                    name = "Trophic Level", labels = c("2.00", "3.48", "3.84", "4.21", "4.65")) +
  scale_fill_manual(values = c("#2a788e", "#355f8d", "#414487", "#482475", "#440154"), 
                    name = "Trophic Level", labels = c("2.00", "3.48", "3.84", "4.21", "4.65")) +
  xlim(NA, 400) + 
  ylim(-1, NA)

p4 <- plot_comparisons(lm2.1, variables = "temp_preferred", condition = list("length", "longevity_wild" = c(1, 10, 16, 25, 50, 100))) +
  labs(
    x = "Optimal Temperature (ºC)",
    y = "PLD Difference with Length",
    color = "Maximum Lifespan (yr)",
    fill = "Maximum Lifespan (yr)"
  ) +
  theme_bw(base_size = 18) +
  scale_color_manual(values = c("#fde725", "#bddf26", "#7ad151", "#44bf70", "#22a884", "#21918c")) +
  scale_fill_manual(values = c("#fde725", "#bddf26", "#7ad151", "#44bf70", "#22a884", "#21918c")) +
  xlim(NA, 45) + 
  ylim(-3.5, 0.5)

plot_comparisons(lm2.1, variables = "length", condition = c("temp_preferred")) +
  labs(
    x = "Length (cm)",
    y = "PLD Difference with Optimal Temperature",
    color = "Maximum Lifespan (yr)",
    fill = "Maximum Lifespan (yr)"
  ) +
  theme_bw() +
  scale_color_viridis_d() +
  scale_fill_viridis_d()

plot_comparisons(lm2.1, variables = "length", condition = c("longevity_wild")) +
  labs(
    x = "Length (cm)",
    y = "PLD Difference with Optimal Temperature",
    color = "Maximum Lifespan (yr)",
    fill = "Maximum Lifespan (yr)"
  ) +
  theme_bw() +
  scale_color_viridis_d() +
  scale_fill_viridis_d()

interact_plot <- (p2 + p4) / (p1 + p3) + plot_layout(guides = "collect") + plot_annotation(tag_levels = "A")
interact_plot

ggsave(interact_plot, file = paste0("interact_plot.pdf"), path = here::here("04_figs", "final_figs"), height = 12, width = 15)

```




### For WSN

```{r}
  
p2 <- plot_comparisons(lm1.1, variables = "temp_preferred", condition = list("length", "longevity_wild" = c(1, 25, 50))) +
  labs(
    x = "Optimal Temperature (ºC)",
    y = "Home Range Difference with Length",
    color = "Maximum Lifespan (yr)",
    fill = "Maximum Lifespan (yr)"
  ) +
  theme_bw(base_size = 18) +
  scale_color_manual(values = c("#7ad151", "#21918c", "#482475")) +
  scale_fill_manual(values = c("#7ad151", "#21918c", "#482475")) +
  xlim(NA, 45) + 
  ylim(-0.25, 0.25)

p4 <- plot_comparisons(lm2.1, variables = "temp_preferred", condition = list("length", "longevity_wild" = c(1, 25, 50))) +
  labs(
    x = "Optimal Temperature (ºC)",
    y = "PLD Difference with Length",
    color = "Maximum Lifespan (yr)",
    fill = "Maximum Lifespan (yr)"
  ) +
  theme_bw(base_size = 18) +
  scale_color_manual(values = c("#7ad151", "#21918c", "#482475")) +
  scale_fill_manual(values = c("#7ad151", "#21918c", "#482475")) +
  xlim(NA, 45) + 
  ylim(-2, 1)

interact_wsn <- (p2 + p4) + plot_layout(guides = "collect") + plot_annotation(tag_levels = "A")
interact_wsn

ggsave(interact_wsn, file = paste0("interact_wsn.pdf"), path = here::here("04_figs", "WSN"), height = 7, width = 15)



# filled_data3 <- filled_data2 %>% 
#   dplyr::select(species, common_name, fb_name, longevity_wild, class2, movement_keyword, observed_pld, predicted_pld, pld, observed_homerange, predicted_homerange, home_range)







```


### Variable Inflation Factors (VIF)

```{r}
model <- lm(
  class3 ~ temp_preferred + fecundity_mean + longevity_wild +
    sp_richness + length + kfin + r_fin + diet_troph3,
  data = filled_data2
)

summary(model)

vif(model) # when including both fecundity variables, they have a VIF over 5

# create vector of VIF values
vif_values <- vif(model)

# create horizontal bar chart to display each VIF value
barplot(vif_values, main = "VIF Values", horiz = TRUE, col = "steelblue", xlim = c(0, 6), las = 2)

# add vertical line at 5
abline(v = 5, lwd = 3, lty = 2)


# model2 <- lm(class2 ~ temp_preferred + length + r_fin, data = filled_data)
# summary(model)
```


### ANOVA/Kruskal-Wallis for Numeric/Continuous Variables

```{r}
# length -------------------------------------------------------

# check for outliers - there are a lot?
outliers_length <- boxplot.stats(filled_data2$length)$out
boxplot(filled_data2$length, main = "Length", boxwex = 0.1)
mtext(paste("Outliers: ", paste(outliers_length, collapse = ", ")), cex = 0.4)

# build the model
model_length <- aov(length ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_length))
# not normal

# model with log transformed length
model_length_log <- aov(log(length) ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_length_log))
# looks normal

# run Shapiro-Wilk test of normality
shapiro_test(residuals(model_length_log))
# p-value = 0.0669, normal

# test for homogeneity of variance
plot(model_length_log, 1)
# looks good

summary(model_length_log)
# p-value < 2e-16 ***

# effect size
effectsize::cohens_f(model_length_log)

effectsize::eta_squared(model_length_log)
interpret_eta_squared(0.18, rules = "cohen1992")
# eta2 = 0.18, LARGE effect

# post hoc Tukey test
TukeyHSD(model_length_log)



# temp_preferred -----------------------------------------------

temp_data <- filled_data2 %>%
  filter(!is.na(temp_preferred)) %>%
  filter(temp_preferred > 0)

# look at outliers
outliers_temp <- boxplot.stats(temp_data$temp_preferred)$out
boxplot(temp_data$temp_preferred, main = "Preferred Temp", boxwex = 0.1)
mtext(paste("Outliers: ", paste(outliers_temp, collapse = ", ")), cex = 0.4)

# build the model
model_temp <- aov(temp_preferred ~ class2, data = temp_data)

# create a QQ plot of residuals
ggqqplot(residuals(model_temp))
# not normal

# model with log transformed variable
model_temp_log <- aov(log(temp_preferred) ~ class2, data = temp_data)

# create a QQ plot of residuals
ggqqplot(residuals(model_temp_log))
# more abnormal

# test for homogeneity of variance
plot(model_temp, 1)
# looks fine

# run Kruskal-Wallis test (non-parametric version of ANOVA)
kruskal.test(temp_preferred ~ class2, data = temp_data)
# chi-squared = 77.77, df = 5, p-value = 2.455e-15

# get effect size 
temp_data %>% kruskal_effsize(temp_preferred ~ class2, ci = TRUE)
# eta2 = 0.124, MODERATE effect

# Kruskal-Wallis is significant, run Dunn's test
dunnTest(temp_preferred ~ class2, data = temp_data, method = "bh")



# longevity_wild -----------------------------------------------

longevity_data <- filled_data2 %>%
  filter(!is.na(longevity_wild))

# look at outliers
outliers_long <- boxplot.stats(longevity_data$longevity_wild)$out
boxplot(longevity_data$longevity_wild, main = "Longevity in the Wild", boxwex = 0.1)
mtext(paste("Outliers: ", paste(outliers_long, collapse = ", ")), cex = 0.4)

# build the model
model_long <- aov(longevity_wild ~ class2, data = longevity_data)

# create a QQ plot of residuals
ggqqplot(residuals(model_long))
# not normal

# model with log transformed variable
model_long_log <- aov(log(longevity_wild) ~ class2, data = longevity_data)

# create a QQ plot of residuals
ggqqplot(residuals(model_long_log))
# almost normal?

# run Shapiro-Wilk test of normality
shapiro_test(residuals(model_long_log))
# p-value = 0.00000807, not normal

# test for homogeneity of variance
plot(model_long, 1)
# looks fine?

# run Kruskal-Wallis test (non-parametric version of ANOVA)
kruskal.test(longevity_wild ~ class2, data = longevity_data)
# chi-squared = 25.928, df = 5, p-value = 9.216e-05

# get effect size 
longevity_data %>% kruskal_effsize(longevity_wild ~ class2, ci = TRUE)
# eta2 = 0.0384, SMALL effect

# Kruskal-Wallis is significant, run Dunn's test
dunnTest(longevity_wild ~ class2, data = longevity_data, method = "bh")



# diet_troph3 --------------------------------------------------

# look at outliers
outliers_diet_troph3 <- boxplot.stats(filled_data2$diet_troph3)$out
boxplot(filled_data2$diet_troph3, main = "Trophic Position", boxwex = 0.1)
mtext(paste("Outliers: ", paste(outliers_diet_troph3, collapse = ", ")), cex = 0.4)

# build the model
model_diet_troph3 <- aov(diet_troph3 ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_diet_troph3))
# not normal

# model with transformed variable
model_diet_troph3_log <- aov(log(diet_troph3) ~ class2, data = filled_data2)
model_diet_troph3_exp <- aov(exp(diet_troph3) ~ class2, data = filled_data2)
model_diet_troph3_sqrt <- aov(sqrt(diet_troph3) ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_diet_troph3_log))
ggqqplot(residuals(model_diet_troph3_exp))
ggqqplot(residuals(model_diet_troph3_sqrt))
# none are normal

# test for homogeneity of variance
plot(model_diet_troph3, 1)
# looks good

# run Kruskal-Wallis test (non-parametric version of ANOVA)
kruskal.test(diet_troph3 ~ class2, data = filled_data2)
# chi-squared = 36.497, df = 5, p-value = 7.555e-07

# get effect size 
filled_data2 %>% kruskal_effsize(diet_troph3 ~ class2, ci = TRUE)
# eta2 = 0.0525, SMALL effect

# Kruskal-Wallis is significant, run Dunn's test
dunnTest(diet_troph3 ~ class2, data = filled_data2, method = "bh")






# kfin ---------------------------------------------------------

# look at outliers
outliers_kfin <- boxplot.stats(filled_data2$kfin)$out
boxplot(filled_data2$kfin, main = "Carrying Capacity", boxwex = 0.1)
mtext(paste("Outliers: ", paste(outliers_kfin, collapse = ", ")), cex = 0.4)

# build the model
model_kfin <- aov(kfin ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_kfin))
# not normal

# model with log transformed variable
model_kfin_log <- aov(log(kfin) ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_kfin_log))
# normal?

# run Shapiro-Wilk test of normality
shapiro_test(residuals(model_kfin_log))
# p-value = 0.00267, not normal

# test for homogeneity of variance
plot(model_kfin, 1)
# looks fine

# run Kruskal-Wallis test (non-parametric version of ANOVA)
kruskal.test(kfin ~ class2, data = filled_data2)
# chi-squared = 61.516, df = 5, p-value = 5.906e-12

# Kruskal-Wallis is significant, run Dunn's test
dunnTest(kfin ~ class2, data = filled_data2, method = "bh")


# r_fin --------------------------------------------------------

# look at outliers
outliers_r_fin <- boxplot.stats(filled_data2$r_fin)$out
boxplot(filled_data2$r_fin, main = "Growth Rate", boxwex = 0.1)
mtext(paste("Outliers: ", paste(outliers_r_fin, collapse = ", ")), cex = 0.4)

# build the model
model_r_fin <- aov(r_fin ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_r_fin))
# not normal

# model with log transformed variable
model_r_fin_log <- aov(log(r_fin) ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_r_fin_log))
# normal?

# run Shapiro-Wilk test of normality
shapiro_test(residuals(model_r_fin_log))
# p-value = 0.000508, not normal

# test for homogeneity of variance
plot(model_r_fin, 1)
# looks fine

# run Kruskal-Wallis test (non-parametric version of ANOVA)
kruskal.test(r_fin ~ class2, data = filled_data2)
# chi-squared = 42.245, df = 5, p-value = 5.255e-08

# Kruskal-Wallis is significant, run Dunn's test
dunnTest(r_fin ~ class2, data = filled_data2, method = "bh")



# fecundity_mean -----------------------------------------------

# look at outliers
outliers_fecundity <- boxplot.stats(filled_data2$fecundity_mean)$out
boxplot(filled_data2$fecundity_mean, main = "Fecundity", boxwex = 0.1)
mtext(paste("Outliers: ", paste(outliers_fecundity, collapse = ", ")), cex = 0.4)

# build the model
model_fecundity <- aov(fecundity_mean ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_fecundity))
# not normal

# model with log transformed variable
model_fecundity_log <- aov(log(fecundity_mean) ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_fecundity_log))
# not normal

# test for homogeneity of variance
plot(model_fecundity, 1)
# not horizontal

# run Kruskal-Wallis test (non-parametric version of ANOVA)
kruskal.test(fecundity_mean ~ class2, data = filled_data2)
# chi-squared = 2.8377, df = 5, p-value = 0.725
# not significant


# sp_richness --------------------------------------------------

# look at outliers
outliers_sp <- boxplot.stats(filled_data2$sp_richness)$out
boxplot(filled_data2$sp_richness, main = "Species Richness by Family", boxwex = 0.1)
mtext(paste("Outliers: ", paste(outliers_sp, collapse = ", ")), cex = 0.4)

# build the model
model_sprich <- aov(sp_richness ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_sprich))
# not normal

# model with log transformed variable
model_sprich_log <- aov(log(sp_richness) ~ class2, data = filled_data2)

# create a QQ plot of residuals
ggqqplot(residuals(model_sprich_log))
# less abnormal

# test for homogeneity of variance
plot(model_sprich, 1)
# looks good

# run Kruskal-Wallis test (non-parametric version of ANOVA)
kruskal.test(sp_richness ~ class2, data = filled_data2)
# chi-squared = 28.128, df = 5, p-value = 3.437e-05

# Kruskal-Wallis is significant, run Dunn's test
dunnTest(sp_richness ~ class2, data = filled_data2, method = "bh")




# temp_range ---------------------------------------------------

temprange_data <- filled_data2 %>%
  filter(!is.na(temp_range))

# look at outliers
outliers_trange <- boxplot.stats(temprange_data$temp_range)$out
boxplot(temprange_data$temp_range, main = "Temperature Range", boxwex = 0.1)
mtext(paste("Outliers: ", paste(outliers_trange, collapse = ", ")), cex = 0.4)

# build the model
model_temprange <- aov(temp_range ~ class2, data = temprange_data)

# create a QQ plot of residuals
ggqqplot(residuals(model_temprange))
# not normal

# model with log transformed variable
model_temprange_log <- aov(log(temp_range) ~ class2, data = temprange_data)

# create a QQ plot of residuals
ggqqplot(residuals(model_temprange_log))
# almost normal?

# run Shapiro-Wilk test of normality
shapiro_test(residuals(model_temprange_log))
# p-value = 0.0000239, not normal

# test for homogeneity of variance
plot(model_temprange, 1)
# looks good

# run Kruskal-Wallis test (non-parametric version of ANOVA)
kruskal.test(temp_range ~ class2, data = temprange_data)
# chi-squared = 19.907, df = 5, p-value = 0.001301

# Kruskal-Wallis is significant, run Dunn's test
dunnTest(temp_range ~ class2, data = temprange_data, method = "bh")


# oxygen_cons --------------------------------------------------

oxygen_data <- filled_data2 %>%
  filter(!is.na(oxygen_cons))

# look at outliers
outliers_ox <- boxplot.stats(oxygen_data$oxygen_cons)$out
boxplot(oxygen_data$oxygen_cons, main = "Oxygen Consumption", boxwex = 0.1)
mtext(paste("Outliers: ", paste(outliers_ox, collapse = ", ")), cex = 0.4)

# build the model
model_oxcons <- aov(oxygen_cons ~ class2, data = oxygen_data)

# create a QQ plot of residuals
ggqqplot(residuals(model_oxcons))
# not normal

# model with log transformed variable
model_oxcons_log <- aov(log(oxygen_cons) ~ class2, data = oxygen_data)

# create a QQ plot of residuals
ggqqplot(residuals(model_oxcons_log))
# not normal

# test for homogeneity of variance
plot(model_oxcons, 1)
# not sure about this?

# run Kruskal-Wallis test (non-parametric version of ANOVA)
kruskal.test(oxygen_cons ~ class2, data = oxygen_data)
# chi-squared = 28.931, df = 5, p-value = 2.392e-05

# Kruskal-Wallis is significant, run Dunn's test
dunnTest(oxygen_cons ~ class2, data = oxygen_data, method = "bh")
```



### Chi-Squared for Categorical Variables

```{r}
# demers_pelag -------------------------------------------------

# Pearson's Chi-squared test
chisq.test(filled_data2$class2, filled_data2$demers_pelag)
# X-squared = 232.88, df = 30, p-value < 2.2e-16 - there is a significant relationship

# contingency table
demers_table <- table(filled_data2$class2, filled_data2$demers_pelag)
demers_table

# post-hoc test
chisq.posthoc.test(demers_table, method = "bonferroni")


# movement_keyword ---------------------------------------------

# Pearson's Chi-squared test
chisq.test(filled_data2$class2, filled_data2$movement_keyword)
# X-squared = 309.78, df = 50, p-value < 2.2e-16

# contingency table
movement_table <- table(filled_data2$class2, filled_data2$movement_keyword)
movement_table

# post-hoc test
chisq.posthoc.test(movement_table, method = "bonferroni")


# body_shape_i -------------------------------------------------

# Pearson's Chi-squared test
chisq.test(filled_data2$class2, filled_data2$body_shape_i)
# X-squared = 28.07, df = 15, p-value = 0.02114

# contingency table
body_table <- table(filled_data2$class2, filled_data2$body_shape_i)
body_table

# post-hoc test
chisq.posthoc.test(body_table, method = "bonferroni")


# climate ------------------------------------------------------

# Pearson's Chi-squared test
chisq.test(filled_data2$class2, filled_data2$climate)
# X-squared = 17.694, df = 5, p-value = 0.003355

# contingency table
climate_table <- table(filled_data2$class2, filled_data2$climate)
climate_table

# post-hoc test
chisq.posthoc.test(climate_table, method = "bonferroni")


# dev_place ----------------------------------------------------

# Pearson's Chi-squared test
chisq.test(filled_data2$class2, filled_data2$dev_place)
# X-squared = 3.5273, df = 5, p-value = 0.6193


# food_mode ----------------------------------------------------

# Pearson's Chi-squared test
chisq.test(filled_data2$class2, filled_data2$food_mode)
# X-squared = 8.4677, df = 5, p-value = 0.1323


# iucn_category ------------------------------------------------

# Pearson's Chi-squared test
chisq.test(filled_data2$class2, filled_data2$iucn_category)
# X-squared = 40.009, df = 25, p-value = 0.0291

# contingency table
iucn_table <- table(filled_data2$class2, filled_data2$iucn_category)
iucn_table

# post-hoc test
chisq.posthoc.test(iucn_table, method = "bonferroni")
```






### Old

##### Similarity percentage

```{r}
# com_data <- filled_data2 %>%
#   dplyr::select(
#     temp_preferred, fecundity_mean, longevity_wild,
#     sp_richness, length, kfin, r_fin, diet_troph3, species, family, class2
#   ) %>%
#   mutate(class2 = as.factor(class2)) %>%
#   filter(temp_preferred > 0) %>%
#   mutate(across(where(is.numeric), ~ scale(.)[, 1])) %>%
#   na.omit()
# 
# com <- com_data %>%
#   dplyr::select(-species, -family, -class2)
# 
# # load from rda in results folder
# # set.seed(123)
# # simper_out = simper(comm = com, group = com_data$class2, permutations = 9999)
# 
# summary(simper_out)
# # shows which traits are primarily responsible for observed difference between classes. traits listed from highest to lowest % contribution to the difference between the two classes (cumsum shows total % contribution to the difference). p is signifigance.
# 
# 
# # load from rda in results folder
# # set.seed(123)
# # ano = anosim(com, com_data$class2, distance = "euclidean", permutations = 9999)
# 
# summary(ano)
# 
# plot(ano)
```


```{r}
# # ocean --------------------------------------------------------
#
# # Pearson's Chi-squared test
# chisq.test(filled_data2$class2, filled_data2$ocean)
# # X-squared = 361.63, df = 126, p-value < 2.2e-16
#
# # contingency table
# ocean_table <- table(filled_data2$class2, filled_data2$ocean)
# ocean_table
#
# # post-hoc test
# chisq.posthoc.test(ocean_table, method = "bonferroni")
#
#
# # basin --------------------------------------------------------
#
# # Pearson's Chi-squared test
# chisq.test(filled_data2$class2, filled_data2$basin)
# # X-squared = 30.172, df = 12, p-value = 0.002631
#
# # contingency table
# basin_table <- table(filled_data2$class2, filled_data2$basin)
# basin_table
#
# # post-hoc test
# chisq.posthoc.test(basin_table, method = "bonferroni")
```
