---
title: "Data Processing for Homerange/PLD Random Forest"
author: "Allie Caughman"
date: "11/13/2021"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(rfishbase)
require(rgbif)
require(rredlist)
```

### Read in data

#### Empirical Home Range Sizes

```{r}
hrs <- read_csv(here("data", "empirical_homeranges.csv")) %>%
  clean_names() %>%
  dplyr::select(-hr_sd) # remove irrelevant columns

clean_taxa = read_csv(here("data", "cleaned_taxonomy.csv")) %>% 
  pull(species) #get list of cleaned taxa

taxa_check = hrs %>% 
  mutate(valid = ifelse(hrs$species %in% clean_taxa, 1, 0)) %>% #assign valid = 1 if hr species is in clean taxa list
  select(valid, species)

sum(taxa_check$valid) == nrow(hrs) #check that the sum of valid is equal to the number of rows in hrs
```

#### Life History Data

```{r}
life_history <- readRDS(here("data", "MegaData_Ray.rds")) %>%
  as.data.frame() %>% # convert to dataframe
  clean_names() %>%
  select(sci_name, r_fin, kfin) # select relevant columns

names(life_history)[names(life_history) == "sci_name"] <- "species" # rename column so that it matches empirical_homeranges.csv

life_history_means <- life_history %>%
  group_by(species) %>%
  summarise(
    kfin = mean(kfin, na.rm = TRUE), # get mean of carrying capacity for each species
    r_fin = mean(r_fin, na.rm = TRUE)) # get mean of growth rate for each species
```

#### IUCN Red List Statuses

```{r}
iucn <- read_csv(here("data", "included_aquamaps_spp_list.csv")) %>%
  clean_names() %>%
  select(valid_sci_name, iucn_category) # select relevant columns

names(iucn)[names(iucn) == "valid_sci_name"] <- "species" # rename column so that it matches homeranges.csv
```

#### Get Data from Fish Base

```{r}
# validate_names(hrs$species) #make sure scientific names are valid

fish <- load_taxa() # 33,124 species

fish_df <- load_taxa() %>%
  as.data.frame() # load same data as dataframe

datLength <- species(fish$Species, fields = c("Species", "Length", "LTypeMaxM", "DemersPelag", "FBname")) # get wanted information from fishbase

datLength <- datLength[datLength$LTypeMaxM %in% c("TL", "FL", "SL"), ] # subset to TL FL and SL lengths

dfdat <- ecology(fish$Species, fields = c("Species", "DietTroph", "DietSeTroph", "FoodTroph", "FoodSeTroph")) # get fish ecology information from fishbase

lm1 <- lm(DietTroph ~ FoodTroph, dfdat, na.action = na.omit) # create linear model to fill in missing trophic data

predDat2 <- merge(datLength, dfdat, by = "Species", all.x = TRUE) # merge length and tropic data

predDat2$DietTroph2 <- with(predDat2, ifelse(is.na(DietTroph), predict(lm1, newdata = data.frame(FoodTroph = FoodTroph)), DietTroph)) # replace NA trophic data with predictions from linear model

predDat2 <- predDat2[, c("Species", "DietTroph2")]

predDat2 <- merge(predDat2, fish_df, by = "Species", all.x = TRUE) # merge data with taxa information

## now predicting missing genuses for dietTroph
missingGen <- unique(predDat2$Genus[is.na(predDat2$DietTroph2)]) # get genuses with NA values

miss_diet <- fish_df %>%
  filter(Genus %in% missingGen) %>% # get missing genuses
  mutate(SpecCode = as.character(SpecCode)) # change SpecCode to a character

grptroph <- ecology(miss_diet$gensp, fields = c("DietTroph", "SpecCode")) %>% # get ecology data of species
  mutate(SpecCode = as.character(SpecCode)) # change SpecCode to a character

d2 <- dplyr::left_join(miss_diet, grptroph) %>% # joining by SpecCode
  group_by(Genus) %>%
  summarize(AvgDietTroph = mean(DietTroph, na.rm = TRUE)) # get mean trophic level by genus

predDat2 <- merge(predDat2, d2, by = "Genus", all.x = T) # merge all data

predDat2$DietTroph3 <- with(predDat2, ifelse(is.na(DietTroph2), AvgDietTroph, DietTroph2)) # replace missing trophic data with genus averages
predDat2$genus <- predDat2$Genus # rename column

fish_df <- fish_df %>%
  rename(spec_code = SpecCode) %>% # rename column
  select(Order, Class, spec_code, Species) %>% # select relevant columns
  rename(species = Species) # rename column

fish_data <- merge(datLength, predDat2) %>%
  clean_names() %>% # clean the names
  dplyr::select(-genus_2, -diet_troph2, -subfamily, -super_class, -avg_diet_troph, -order, -class) # merge all data and remove columns that are not relevant

fish_data_o <- left_join(fish_df, fish_data) %>%
  select(species, Class, demers_pelag, family) # merge all data

fish_data_means <- left_join(fish_df, fish_data) %>%
  group_by(species) %>%
  summarise(
    length = mean(length, na.rm = TRUE), # get mean length by species
    diet_troph3 = mean(diet_troph3, na.rm = TRUE)
  ) # get mean trophic level for species

fish_data <- left_join(fish_data_means, fish_data_o, by = "species") %>%
  distinct() # get all the data for each fish species with length and trophic level data
```

#### Mobility Data

```{r}
mobility_data <- read_csv(here("data", "movement_classification.csv")) %>%
  select(species, movement_keyword, m_fin) # select relevant columns
```

#### Geographic ranges

```{r}
geog <- read_csv(here("data", "geog_range.csv")) %>%
  rename(species = SciName) %>% # rename column
  select(species, geog_range) # select desired columns

species_list <- geog %>%
  pull(species) # get list of 811 species
```

### Merge all Data

```{r}
join1 <- full_join(hrs, life_history_means) %>% # merge home range data with life history data
  filter(species %in% geog$species) %>% # filter by species list in geog range data set
  distinct() %>% # get distinct values
  filter(!is.na(kfin)) %>% # remove missing carrying capacities
  filter(!is.na(r_fin)) # remove missing growth rates

join2 <- left_join(join1, iucn) %>% # merge data with IUCN data
  select(-family) # remove unneeded column

join3 <- left_join(join2, fish_data) %>% # join data with fishbase data
  filter(!is.na(length)) %>% # remove missing lengths
  filter(!is.na(diet_troph3)) # remove missing trophic levels

join4 <- left_join(join3, mobility_data) # join data with movement data

join5 <- left_join(join4, geog) %>% # join data with geographic ranges
  filter(!is.na(geog_range)) %>% # remove missing geographic ranges
  select(species, common_name, homerange, n_ind, kfin, r_fin, iucn_category, length, diet_troph3, Class, demers_pelag, family, movement_keyword, geog_range, m_fin) # select all desired columns

write_csv(join5, here::here("data", "randomforest_data.csv")) #write csv last written 10/11/2022
```
