---
title: "HR VS PLD"
author: "Allie Caughman"
date: "2/16/2022"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(ggpubr)
library(EnvStats)
library(dbscan)
library(fitdistrplus)
library(mixtools)
library(logspline)
library(plyr)
library(MASS)
library(ggforce)
library(factoextra)
library(NbClust)
library(mclust)
library(tidyverse)
```

### Read in Data

```{r}
pld_hr = read_csv(here::here("01_data", "02_processed_data", "filled_data2.csv")) %>%
  mutate_if(is.character, as.factor)
```

### Explore data

```{r}
p1 = ggplot(pld_hr, aes(log(home_range), pld)) +
  geom_point() +
  theme_bw() +
  labs(x = "ln(Predicted Homerange)",
       y = "Predicted PLD")
p1

# ggsave(p1, file = paste0("data_fig.pdf"), path = here::here("04_figs"))
```


```{r}
ggplot(pld_hr, aes(log(home_range), pld)) +
  geom_point() +
  theme_bw() +
  facet_wrap(~movement_keyword) +
  geom_smooth(method = "lm", se = FALSE) +
  stat_cor(label.y = 90)
```

```{r, include = FALSE}
ggplot(pld_hr, aes(log(home_range), pld)) +
  geom_point() +
  theme_bw() +
  facet_wrap(~demers_pelag) +
  geom_smooth(method = "lm", se = FALSE) +
  stat_cor(label.y = 90)
```

```{r, include = FALSE}
ggplot(pld_hr, aes(log(home_range), pld)) +
  geom_point() +
  theme_bw() +
  facet_wrap(~basin) +
  geom_smooth(method = "lm", se = FALSE) +
  stat_cor(label.y = 90)
```

```{r, include = FALSE}
ggplot(pld_hr, aes(log(home_range), pld)) +
  geom_point() +
  theme_bw() +
  facet_wrap(~dev_place) +
  geom_smooth(method = "lm", se = FALSE) +
  stat_cor(label.y = 90)
```

Family with > 5 representatives

```{r, include = FALSE}
fam_sum <- pld_hr %>%
  group_by(family) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  filter(count > 5)

fam_data <- pld_hr %>%
  filter(family %in% fam_sum$family)
```

```{r}
ggplot(fam_data, aes(log(home_range), pld)) +
  geom_point() +
  theme_bw() +
  facet_wrap(~family) +
  geom_smooth(method = "lm", se = FALSE) +
  stat_cor(label.y = 75)
```

### Modeling

```{r}
lm1 = lm(pld ~ home_range, data = pld_hr)

summary(lm1)

lm2 = lm(home_range ~ pld, data = pld_hr)

summary(lm2)
```


### Clustering 

```{r, include = FALSE}
pld_data <- pld_hr %>%
  dplyr::select(pld)
hr_data <- pld_hr %>%
  dplyr::select(home_range) %>%
  mutate(home_range = log(home_range))

pld_km <- kmeans(pld_data, 3)
hr_km <- kmeans(hr_data, 3)

pld_hr$pld_clusters <- pld_km$cluster
pld_hr$hr_clusters <- hr_km$cluster

pld_hr <- pld_hr %>%
  mutate(hr_clusters = as.factor(hr_clusters))
pld_hr <- pld_hr %>%
  mutate(pld_clusters = as.factor(pld_clusters))

ggplot(pld_hr, aes(x = log(home_range), y = pld)) +
  geom_jitter(aes(color = hr_clusters)) +
  theme_bw()
ggplot(pld_hr, aes(x = log(home_range), y = pld)) +
  geom_jitter(aes(color = pld_clusters)) +
  theme_bw()
```

Gaussian Mixture Model

```{r}
gmm_data_log <- pld_hr %>%
  dplyr::select(home_range, pld) %>%
  mutate(home_range = log(home_range))

gmm_mclust <- Mclust(gmm_data_log)

summary(gmm_mclust)

plot(gmm_mclust, what = "classification")
```

```{r}
gmm_data <- pld_hr %>%
  dplyr::select(home_range, pld) %>%
  mutate(log_home_range = log(home_range)) %>%
  filter(log_home_range < 5) %>%
  dplyr::select(-log_home_range)

gmm_mclust <- Mclust(gmm_data)

summary(gmm_mclust)

plot(gmm_mclust, what = "classification", xlim = c(0, 1))
```



```{r, include = FALSE}
hr <- data %>%
  pull(home_range)

pld <- data %>%
  pull(pld)

MASS::boxcox(pld ~ hr)

bc_hr <- 1 / sqrt(hr)
```

```{r, include = FALSE}
descdist(bc_hr, discrete = FALSE)
descdist(pld, discrete = FALSE)

fit.pld.lognorm <- fitdist(pld, "lnorm")
fit.pld.weibull <- fitdist(pld, "weibull")
fit.pld.gamma <- fitdist(pld, "gamma")

c(fit.pld.lognorm$loglik, fit.pld.weibull$loglik, fit.pld.gamma$loglik)

plot(fit.pld.lognorm)
```

```{r, include = FALSE}
fit.hr <- spEMsymloc(bc_hr, mu0 = c(3, 28))
fit.hr.norm <- normalmixEM(bc_hr)

fit.hr.norm$loglik

plot(fit.hr)
lines(density(bc_hr), lty = 2, lwd = 2)

plot(fit.hr.norm, which = 2)
lines(density(bc_hr), lty = 2, lwd = 2)
```
