---
title: "Fishbase"
author: "Allie Caughman"
date: "2023-05-03"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(rfishbase)
library(naniar)
```

```{r}
pisco_species = read_csv(here::here("01_data", "02_processed_data", "pisco_species.csv")) %>% 
  unique() %>% 
  filter(!is.na(species))
```

```{r}
data <- read_csv(here("01_data", "01_raw_data", "randomforest_data.csv"))

data = left_join(pisco_species, data, multiple = "all") %>% 
  select(genus, species, r_fin, kfin, length, diet_troph3, movement_keyword, geog_range) %>% 
  unique()

```

```{r}
fish <- load_taxa() %>%  # load all taxonomic info from fishbase into fish, then
  janitor::clean_names()

fish_df = load_taxa() %>% 
  as.data.frame()
```

```{r}
datLength <- species(fish$species, fields = c("Species", "Length", "LTypeMaxM", "DemersPelag", "FBname")) # get wanted information from fishbase

datLength <- datLength[datLength$LTypeMaxM %in% c("TL", "FL", "SL"), ] # subset to TL FL and SL lengths

dfdat <- ecology(fish$species, fields = c("Species", "DietTroph", "DietSeTroph", "FoodTroph", "FoodSeTroph")) # get fish ecology information from fishbase

growth <- popgrowth(fish$species, c("Species", "Rm")) %>% 
  na.omit() %>% 
  filter(Species %in% data$species)

# gg_miss_var(datLength) + # figure showing the missing data
#   theme_bw()
# gg_miss_var(dfdat) + # figure showing the missing data
#   theme_bw()

lm1 <- lm(DietTroph ~ FoodTroph, dfdat, na.action = na.omit) # create linear model to fill in missing trophic data

predDat2 <- merge(datLength, dfdat, by = "Species", all.x = TRUE) # merge length and tropic data

predDat2$DietTroph2 <- with(predDat2, ifelse(is.na(DietTroph), predict(lm1, newdata = data.frame(FoodTroph = FoodTroph)), DietTroph)) # replace NA trophic data with predictions from linear model

predDat2 <- predDat2[, c("Species", "DietTroph2")]

predDat2 <- merge(predDat2, fish_df, by = "Species", all.x = TRUE) # merge data with taxa information

## now predicting missing genuses for dietTroph
missingGen <- unique(predDat2$Genus[is.na(predDat2$DietTroph2)]) # get genuses with NA values

miss_diet <- fish_df %>%
  filter(Genus %in% missingGen) %>% # get missing genuses
  mutate(SpecCode = as.character(SpecCode)) # change SpecCode to a character

grptroph <- ecology(miss_diet$gensp, fields = c("DietTroph", "SpecCode")) %>% # get ecology data of species
  mutate(SpecCode = as.character(SpecCode)) # change SpecCode to a character

d2 <- dplyr::left_join(miss_diet, grptroph) %>% # joining by SpecCode
  group_by(Genus) %>%
  summarize(AvgDietTroph = mean(DietTroph, na.rm = TRUE)) # get mean trophic level by genus

predDat2 <- merge(predDat2, d2, by = "Genus", all.x = T) # merge all data

predDat2$DietTroph3 <- with(predDat2, ifelse(is.na(DietTroph2), AvgDietTroph, DietTroph2)) # replace missing trophic data with genus averages
predDat2$genus <- predDat2$Genus # rename column

fish_df <- fish_df %>%
  rename(spec_code = SpecCode) %>% # rename column
  select(Order, Class, spec_code, Species) %>% # select relevant columns
  rename(species = Species) # rename column

fish_data <- merge(datLength, predDat2) %>%
  janitor::clean_names() %>% # clean the names
  dplyr::select(-genus_2, -diet_troph2, -subfamily, -super_class, -avg_diet_troph, -order, -class) # merge all data and remove columns that are not relevant

fish_data_o <- left_join(fish_df, fish_data) %>%
  select(species, Class, demers_pelag, family) # merge all data

fish_data_means <- left_join(fish_df, fish_data) %>%
  group_by(species) %>%
  summarise(
    length = mean(length, na.rm = TRUE), # get mean length by species
    diet_troph3 = mean(diet_troph3, na.rm = TRUE)
  ) # get mean trophic level for species

fish_data <- left_join(fish_data_means, fish_data_o, by = "species") %>%
  distinct() %>% # get all the data for each fish species with length and trophic level data
  filter(species %in% data$species) %>% 
  na.omit() %>% 
  select(-Class, -family)
```

```{r}
gg_miss_var(fish_data) + # figure showing the missing data
  theme_bw()
```

```{r}
data_1 = data %>%
  na.omit()

data = full_join(data_1, fish_data) %>% 
  mutate(movement_keyword = case_when(
    !is.na(movement_keyword) ~ movement_keyword,
    is.na(movement_keyword) & demers_pelag == "reef-associated" ~ "habitat_reef",
    is.na(movement_keyword) & demers_pelag == "pelagic-oceanic" ~ "pelagic",
    is.na(movement_keyword) & demers_pelag == "demersal" ~ "habitat_benthic",
    is.na(movement_keyword) & demers_pelag == "pelagic-neritic" ~ "pelagic",
    is.na(movement_keyword) & demers_pelag == "benthopelagic" ~ "habitat_deep",
    is.na(movement_keyword) & demers_pelag == "bathydemersal" ~ "habitat_deep",
  )) %>% 
  select(-demers_pelag)
```



```{r}

```


### Need to find kfin and rfin, calculate movement keyword, get geographic range
